begin;
create extension if not exists pgtap with schema extensions;
select plan(12);
select has_function('public','owner_bunker_v2_seed_test_guests',array['uuid','integer'],'test guest seeding exists');
select has_function('public','owner_prepare_bunker_v2_test',array['uuid','uuid'],'test prepare exists');
select has_function('public','owner_bunker_v2_test_accelerate',array['uuid','integer'],'test timer acceleration exists');
select has_function('public','owner_bunker_v2_test_simulate_current',array['uuid'],'test stage simulation exists');
select has_function('public','owner_bunker_v2_test_set_inventory',array['uuid','integer','text','integer'],'test inventory control exists');
select has_function('public','owner_bunker_v2_test_set_wagon_state',array['uuid','integer','text','text','text'],'test wagon state control exists');
select has_function('public','owner_bunker_v2_reset_game_and_registrations',array['uuid','text'],'game+registration reset exists');
select ok(pg_get_functiondef('public.owner_bunker_v2_test_accelerate(uuid,integer)'::regprocedure)~'game_mode.*test','timer acceleration is test-only');
select ok(pg_get_functiondef('public.owner_bunker_v2_test_set_inventory(uuid,integer,text,integer)'::regprocedure)~'game_mode.*test','inventory editing is test-only');
select ok(not has_function_privilege('anon','public.owner_bunker_v2_test_simulate_current(uuid)','EXECUTE'),'anonymous users cannot simulate');
select ok(not has_function_privilege('anon','public.owner_bunker_v2_reset_game_and_registrations(uuid,text)','EXECUTE'),'anonymous users cannot reset registrations');
select ok(pg_get_functiondef('public.owner_bunker_v2_reset_game_and_registrations(uuid,text)'::regprocedure)~'couple_preanswers' = false,'game registration reset does not delete couple preanswers');
select * from finish();rollback;
