import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { getSupabaseClient } from '../../../lib/supabase'; import { applyCarriageDistribution,loadOwnerDashboard,type AdminDashboard,type AdminRpcClient } from '../admin.service'; import type { SupportedCarriageCount } from '../../carriages/carriageAllocator'; import { AdminBunkerControl,type AdminBunkerControlDependencies } from './AdminBunkerControl'; import type { MissionOneOwnerReadModel as M1Panel } from './MissionOneOwnerPanel'; import { MissionTwoOwnerPanel,type MissionTwoOwnerPanelModel } from './MissionTwoOwnerPanel'; import { getOwnerMissionOneReadModel,overrideMissionOneSelection,type MissionOneOwnerReadModel,type MissionOneRpcClient,type OverrideMissionOneSelectionInput } from '../../bunker/v2/m01.service'; import { getOwnerMissionTwoReadModel,type MissionTwoOwnerReadModel } from '../../bunker/v2/m02.service'; import { broadcastBunkerRefresh,subscribeToBunkerRefresh,type BunkerRealtimeClient } from '../../bunker/bunker.realtime'; import { isOwnerSessionExpired } from '../ownerSession';
const EVENT_SLUG='liza-viktor';
export type AdminBunkerDockDependencies={loadDashboard:()=>Promise<AdminDashboard>;applyDistribution:(eventId:string,carriageCount:SupportedCarriageCount)=>Promise<unknown>;bunkerControl?:AdminBunkerControlDependencies;loadMissionOne?:(eventId:string)=>Promise<MissionOneOwnerReadModel>;overrideMissionOne?:(input:OverrideMissionOneSelectionInput)=>Promise<unknown>;loadMissionTwo?:(eventId:string)=>Promise<MissionTwoOwnerReadModel>;broadcastRefresh?:()=>Promise<void>;subscribeRefresh?:(callback:()=>void)=>()=>void}; type Props={dependencies?:AdminBunkerDockDependencies;pollIntervalMs?:number};
function browserDependencies():AdminBunkerDockDependencies|null{try{const client=getSupabaseClient()as unknown as AdminRpcClient&MissionOneRpcClient&BunkerRealtimeClient;return{loadDashboard:()=>loadOwnerDashboard(client,EVENT_SLUG),applyDistribution:(eventId,count)=>applyCarriageDistribution(client,eventId,count),loadMissionOne:(eventId)=>getOwnerMissionOneReadModel(client,eventId),overrideMissionOne:(input)=>overrideMissionOneSelection(client,input),loadMissionTwo:(eventId)=>getOwnerMissionTwoReadModel(client,eventId),broadcastRefresh:()=>broadcastBunkerRefresh(client,EVENT_SLUG),subscribeRefresh:(callback)=>subscribeToBunkerRefresh(client,EVENT_SLUG,callback)};}catch{return null;}}
function secs(deadlineAt:string,serverNow:string){return Math.max(0,Math.ceil((Date.parse(deadlineAt)-Date.parse(serverNow))/1000));} function m1Panel(model:MissionOneOwnerReadModel|null):M1Panel|undefined{if(!model||model.contractVersion!==2||model.status!=='active')return;return{status:model.wagons.every(w=>w.status==='completed')?'completed':'active',remainingSeconds:secs(model.deadlineAt,model.serverNow),wagons:model.wagons};} function m2Panel(model:MissionTwoOwnerReadModel|null):MissionTwoOwnerPanelModel|undefined{if(!model||model.contractVersion!==2||model.status!=='active')return;return{status:'active',title:model.title,remainingSeconds:secs(model.deadlineAt,model.serverNow),wagons:model.wagons};} function commandId(){return globalThis.crypto?.randomUUID?.()??`owner-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
export function AdminBunkerDock({dependencies,pollIntervalMs=15000}:Props={}){const deps=useMemo(()=>dependencies??browserDependencies(),[dependencies]);const[dashboard,setDashboard]=useState<AdminDashboard|null>(null),[m1,setM1]=useState<MissionOneOwnerReadModel|null>(null),[m2,setM2]=useState<MissionTwoOwnerReadModel|null>(null),[lastSuccessAt,setLastSuccessAt]=useState<string|null>(null),[availability,setAvailability]=useState<'loading'|'current'|'stale'|'unavailable'>(deps?'loading':'unavailable');const dashboardRef=useRef<AdminDashboard|null>(null),mountedRef=useRef(false),activePollRequestRef=useRef<number|null>(null),commandInFlightRef=useRef(false),latestRequestRef=useRef(0);
const storeDashboard=useCallback((next:AdminDashboard)=>{dashboardRef.current=next;setDashboard(next);setLastSuccessAt(new Date().toISOString());setAvailability('current');},[]);const failClosed=useCallback(()=>{dashboardRef.current=null;setDashboard(null);setLastSuccessAt(null);setAvailability('unavailable');setM1(null);setM2(null);},[]);const handleFailure=useCallback((error:unknown)=>{if(isOwnerSessionExpired(error)||!dashboardRef.current){failClosed();return;}setAvailability('stale');},[failClosed]);
const loadMissionReads=useCallback(async(next:AdminDashboard,requestId?:number)=>{const active=()=>mountedRef.current&&(requestId===undefined||requestId===latestRequestRef.current);if(deps?.loadMissionOne)void deps.loadMissionOne(next.event.id).then(value=>{if(active())setM1(value);}).catch(()=>{});if(deps?.loadMissionTwo)void deps.loadMissionTwo(next.event.id).then(value=>{if(active())setM2(value);}).catch(()=>{});},[deps]);
const pollDashboard=useCallback(async()=>{if(!deps||commandInFlightRef.current)return;const activeId=activePollRequestRef.current;if(activeId!==null&&activeId===latestRequestRef.current)return;const requestId=++latestRequestRef.current;activePollRequestRef.current=requestId;try{const next=await deps.loadDashboard();if(mountedRef.current&&requestId===latestRequestRef.current)storeDashboard(next);void loadMissionReads(next,requestId);}catch(error){if(mountedRef.current&&requestId===latestRequestRef.current)handleFailure(error);}finally{if(activePollRequestRef.current===requestId)activePollRequestRef.current=null;}},[deps,handleFailure,loadMissionReads,storeDashboard]);
const refreshMissions=useCallback(async()=>{const current=dashboardRef.current;if(!current){void pollDashboard();return;}void loadMissionReads(current);},[loadMissionReads,pollDashboard]);
useEffect(()=>{if(!deps)return;mountedRef.current=true;void pollDashboard();const interval=window.setInterval(()=>void pollDashboard(),pollIntervalMs);const recover=()=>void pollDashboard();const unsubscribe=deps.subscribeRefresh?.(()=>void refreshMissions());window.addEventListener('focus',recover);window.addEventListener('online',recover);return()=>{mountedRef.current=false;latestRequestRef.current+=1;activePollRequestRef.current=null;window.clearInterval(interval);window.removeEventListener('focus',recover);window.removeEventListener('online',recover);unsubscribe?.();};},[deps,pollDashboard,pollIntervalMs,refreshMissions]);
const acceptDistribution=async(count:SupportedCarriageCount)=>{if(!deps||commandInFlightRef.current||!dashboardRef.current)return;commandInFlightRef.current=true;latestRequestRef.current+=1;const eventId=dashboardRef.current.event.id;try{await deps.applyDistribution(eventId,count);const requestId=++latestRequestRef.current;const fresh=await deps.loadDashboard();if(mountedRef.current&&requestId===latestRequestRef.current)storeDashboard(fresh);void loadMissionReads(fresh,requestId);}finally{commandInFlightRef.current=false;}};
const applyM1Override=async(override:{wagonId:string;selectedGuestIds:string[];reason:string})=>{if(!deps?.overrideMissionOne||!dashboardRef.current)return;const wagon=m1?.contractVersion===2&&m1.status==='active'?m1.wagons.find(c=>c.wagonId===override.wagonId):undefined;if(!wagon)throw new Error('M01 wagon snapshot is unavailable');await deps.overrideMissionOne({eventId:dashboardRef.current.event.id,instanceId:wagon.instanceId,instanceVersion:wagon.instanceVersion,commandId:commandId(),selectedGuestIds:override.selectedGuestIds,reason:override.reason});try{await deps.broadcastRefresh?.();}catch{}void refreshMissions();};
if(!deps||availability==='unavailable')return<aside id="admin-bunker" className="admin-bunker-dock" aria-label="Экстренный сюжетный поворот"><div className="admin-bunker-dock__unavailable" role="status"><strong>OWNER-ДАННЫЕ НЕДОСТУПНЫ</strong><span>ПУЛЬТ СКРЫТ · ПРОВЕРЬТЕ OWNER-СЕССИЮ И СВЯЗЬ</span></div></aside>;
if(!dashboard||availability==='loading')return<aside id="admin-bunker" className="admin-bunker-dock" aria-label="Экстренный сюжетный поворот"><div className="admin-bunker-dock__freshness" role="status"><span>OWNER-ДОСТУП · ПРОВЕРЯЕМ</span></div></aside>;
const missionTwo=m2Panel(m2);return<aside id="admin-bunker" className="admin-bunker-dock" aria-label="Экстренный сюжетный поворот">{lastSuccessAt&&<div className="admin-bunker-dock__freshness" role="status"><span>{availability==='stale'?'OWNER-ДАННЫЕ СОХРАНЕНЫ · ПЕРЕПОДКЛЮЧЕНИЕ':'OWNER-ДАННЫЕ ПОДТВЕРЖДЕНЫ'}</span><time dateTime={lastSuccessAt}>{new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(lastSuccessAt))}</time></div>}<AdminBunkerControl eventId={dashboard.event.id} dependencies={deps.bunkerControl} dashboard={dashboard} onAcceptDistribution={acceptDistribution} bunkerContractVersion={m1?.contractVersion??m2?.contractVersion} missionOne={m1Panel(m1)} onMissionOneOverride={deps.overrideMissionOne?applyM1Override:undefined}/>{missionTwo&&<MissionTwoOwnerPanel model={missionTwo}/>}</aside>;
}
