import type { BunkerMissionStage, GuestBunkerQuestState } from '../bunker/bunkerQuest.types';
import { BunkerPlayerDashboard } from '../bunker/BunkerPlayerDashboard';
import { isLegacyActiveGuestBunkerRuntime, type GuestBunkerReadRuntime } from '../bunker/bunkerRuntime.service';
import type { GuestCarriageCall } from '../carriages/carriageCalls.service';
import type { MissionOnePlayerReadModel } from '../bunker/v2/MissionOnePlayer';
import type { MissionTwoPlayerReadModel } from '../bunker/v2/MissionTwoPlayer';
import type { RegisteredGuest } from '../registration/registration.types';
import { VirtualTicket } from '../registration/VirtualTicket';
import type { GuestQuizState, QuizChoice, QuizHistoryEntry } from '../quiz/quiz.service';
import { GuestLiveActivity } from './GuestLiveActivity';

type GuestHubProps = {
  guest: RegisteredGuest; activeCall: GuestCarriageCall | null; bunkerState?: GuestBunkerQuestState | null; bunkerRuntime?: GuestBunkerReadRuntime | null;
  bunkerMissionOne?: MissionOnePlayerReadModel; bunkerMissionTwo?: MissionTwoPlayerReadModel; bunkerRuntimeLoading?: boolean; bunkerRuntimeError?: string; bunkerFeedback?: string; bunkerError?: string; bunkerSubmitting?: boolean;
  onBunkerMission?: (stage: BunkerMissionStage, answer: string) => void; onBunkerFinalCode?: (code: string) => void; onConfirmBunkerMissionOne?: (selectedGuestIds: string[]) => Promise<void>|void;
  onSubmitBunkerMissionTwo?: (answers: string[]) => Promise<void>|void; onUseBunkerMissionTwoAbility?: (ability: 'system_access'|'terminal_hack') => Promise<void>|void;
  quizState: GuestQuizState | null; quizError?: string; quizSubmitting?: QuizChoice | null; onQuizVote: (choice: QuizChoice) => void; onQuizDeadline?: () => void;
};
function percentage(value:number,total:number){return total>0?Math.round(value/total*100):0;} function historyFrom(state:GuestQuizState|null):QuizHistoryEntry[]{return state&&'history'in state&&state.history?state.history:[];}
function bunkerStatus(state:GuestBunkerQuestState|null):string{if(!state||state.status!=='active')return'ОЖИДАЕМ ЗАПУСК';switch(state.phase){case'emergency':return'ЭКСТРЕННОЕ СООБЩЕНИЕ';case'dossier_1':return'ДОСЬЕ · ЭТАП I';case'dossier_2':return'ДОСЬЕ · ЭТАП II';case'mission_a':return'КОМАНДНОЕ ЗАДАНИЕ';case'mission_b':return'ОБЩЕЕ ЗАДАНИЕ';case'final':return state.final.unlocked?'ДОСТУП ПОЛУЧЕН':'ФИНАЛЬНЫЙ ДОСТУП';case'completed':return'БУНКЕР ОТКРЫТ';}}
export function GuestHub({guest,activeCall,bunkerState=null,bunkerRuntime=null,bunkerMissionOne,bunkerMissionTwo,bunkerRuntimeLoading=false,bunkerRuntimeError='',bunkerFeedback='',bunkerError='',bunkerSubmitting=false,onBunkerMission=()=>undefined,onBunkerFinalCode=()=>undefined,onConfirmBunkerMissionOne,onSubmitBunkerMissionTwo,onUseBunkerMissionTwoAbility,quizState,quizError='',quizSubmitting=null,onQuizVote,onQuizDeadline}:GuestHubProps){
  const activeV2=Boolean(bunkerRuntime&&bunkerRuntime.status==='active'&&'contractVersion'in bunkerRuntime&&bunkerRuntime.contractVersion===2);
  if(bunkerRuntime&&(isLegacyActiveGuestBunkerRuntime(bunkerRuntime)||activeV2))return <main className="bunker-player-shell theme-bunker"><BunkerPlayerDashboard runtime={bunkerRuntime as Parameters<typeof BunkerPlayerDashboard>[0]['runtime']} connectionError={bunkerRuntimeError} missionOne={bunkerMissionOne} missionTwo={bunkerMissionTwo} onConfirmMissionOne={onConfirmBunkerMissionOne} onSubmitMissionTwo={onSubmitBunkerMissionTwo} onUseMissionTwoAbility={onUseBunkerMissionTwoAbility}/></main>;
  const history=historyFrom(quizState); const quizStatus=quizState?.status==='active'?(quizState.phase==='voting'?'ИДЁТ ГОЛОСОВАНИЕ':'ПОКАЗЫВАЕМ РЕЗУЛЬТАТ'):'ОЖИДАЕМ ВОПРОС';
  return <main className="guest-hub"><header className="guest-hub-header"><div><p className="eyebrow">ЛИЗА × ВИКТОР · 30.08.2026</p><h1>ВАШ ВЕЧЕР</h1><p>{guest.firstName}, держите эту страницу открытой — активности будут появляться здесь сами.</p></div><span className="guest-hub-online">LIVE</span></header>
  <section className="guest-hub-section guest-hub-now" aria-label="Сейчас происходит"><div className="guest-hub-section-heading"><p className="eyebrow">СЕЙЧАС ПРОИСХОДИТ</p><span>ОБНОВЛЯЕТСЯ АВТОМАТИЧЕСКИ</span></div><GuestLiveActivity carriage={guest.carriage} activeCall={activeCall} bunkerState={bunkerState} bunkerFeedback={bunkerFeedback||bunkerError} bunkerSubmitting={bunkerSubmitting} onBunkerMission={onBunkerMission} onBunkerFinalCode={onBunkerFinalCode} quizState={quizState} quizError={quizError} quizSubmitting={quizSubmitting} onQuizVote={onQuizVote} onQuizDeadline={onQuizDeadline}/></section>
  {bunkerRuntimeLoading&&<p className="guest-hub-notice" role="status">Проверяем защищённый канал Бункера. Ваш билет и остальные активности остаются доступны.</p>}{bunkerRuntimeError&&<p className="guest-hub-notice" role="alert">{bunkerRuntimeError}</p>}
  <section className="guest-hub-section guest-hub-ticket" aria-label="Мой билет"><div className="guest-hub-section-heading"><p className="eyebrow">МОЙ БИЛЕТ</p></div><VirtualTicket guest={guest}/></section>
  <section className="guest-hub-section" aria-label="Мои активности"><div className="guest-hub-section-heading"><p className="eyebrow">МОИ АКТИВНОСТИ</p></div><div className="guest-hub-activity-grid"><article className={bunkerState?.status==='active'?'guest-hub-activity--active':''}><span>БУНКЕР</span><strong>{bunkerStatus(bunkerState)}</strong><p>Экстренный протокол, личное досье и задания вагона появятся здесь автоматически.</p></article><article><span>LIVE QUIZ</span><strong>{quizStatus}</strong><p>Вопрос появится здесь автоматически — переходить на отдельную страницу не нужно.</p></article><a className="guest-hub-activity-link guest-event-action--mk" href="/mortal-kombat" aria-label="ПОСЛЕДНИЙ КРУГ · УЧАСТВОВАТЬ"><span>ПОСЛЕДНИЙ КРУГ</span><strong>ОТКРЫТЬ АРЕНУ</strong><p>Регистрация и статус турнира. После проверки вернитесь сюда.</p></a></div></section>
  <section className="guest-hub-section guest-hub-inventory" aria-label="Инвентарь"><div className="guest-hub-section-heading"><p className="eyebrow">ИНВЕНТАРЬ</p><span>БУНКЕР · ЛИЧНОЕ СНАРЯЖЕНИЕ</span></div><div className="guest-hub-inventory__empty"><picture className="generated-artwork-picture" aria-hidden="true"><source type="image/avif" srcSet="/images/ticket/railway-seal-128.avif 128w, /images/ticket/railway-seal-256.avif 256w" sizes="72px"/><source type="image/webp" srcSet="/images/ticket/railway-seal-128.webp 128w, /images/ticket/railway-seal-256.webp 256w" sizes="72px"/><img src="/images/ticket/railway-seal.png" alt="" width="256" height="256"/></picture><div className="guest-hub-inventory__copy"><strong>ИНВЕНТАРЬ ПУСТ</strong><p>Предметы вагона появятся здесь после запуска Бункера и будут обновляться автоматически.</p><span className="guest-hub-inventory__status">ПОЯВИТСЯ ПОСЛЕ ЗАПУСКА БУНКЕРА</span></div></div></section>
  <section className="guest-hub-section guest-hub-history" aria-label="История вечера"><div className="guest-hub-section-heading"><p className="eyebrow">ИСТОРИЯ ВЕЧЕРА</p><span>{history.length} ЗАВЕРШЕНО</span></div>{history.length===0?<p className="guest-hub-empty">Здесь появятся уже завершённые вопросы и события.</p>:<div className="guest-hub-history-list">{history.slice(0,8).map((entry)=><article key={entry.roundId}><div><span>LIVE QUIZ</span><strong>{entry.questionText}</strong></div><div className="guest-hub-history-result"><span>Л {percentage(entry.results.liza,entry.results.total)}%</span><span>В {percentage(entry.results.viktor,entry.results.total)}%</span>{entry.selectedChoice&&<small>ВАШ ОТВЕТ · {entry.selectedChoice==='liza'?'ЛИЗА':'ВИКТОР'}</small>}</div></article>)}</div>}</section></main>;
}
