import { type ReactNode, useEffect, useRef, useState } from 'react';
import { getSupabaseClient } from '../../lib/supabase';
import { BunkerEmergencyScene } from './BunkerEmergencyScene';
import { BunkerQuestScene, phaseForGlobalGameState } from './BunkerQuestScene';
import { createBunkerAudioController, type BunkerAudioController } from './bunkerAudio';
import { setBunkerPresentationProtected } from './bunkerProtection';
import { subscribeToBunkerRefresh, type BunkerRealtimeClient } from './bunker.realtime';
import { getBunkerScreenState, type BunkerRpcClient, type BunkerScreenState } from './bunker.service';
import { getMissionOneScreenReadModel, type MissionOneRpcClient, type MissionOneScreenReadModel as M01Service } from './v2/m01.service';
import type { MissionOneScreenReadModel } from './v2/MissionOneScreen';
import { getMissionTwoScreenReadModel, type MissionTwoScreenReadModel as M02Service } from './v2/m02.service';
import type { MissionTwoScreenModel } from './v2/MissionTwoScreen';
import { getMissionThreeScreenReadModel, type MissionThreeScreenReadModel as M03Service } from './v2/m03.service';
import type { MissionThreeScreenModel } from './v2/MissionThreeScreen';
import { getMissionFourScreenReadModel, type MissionFourScreenReadModel as M04Service } from './v2/m04.service';
import type { MissionFourScreenModel } from './v2/MissionFourScreen';

export type BunkerScreenGuardDependencies={load:()=>Promise<BunkerScreenState>;loadMissionOne?:()=>Promise<M01Service>;loadMissionTwo?:()=>Promise<M02Service>;loadMissionThree?:()=>Promise<M03Service>;loadMissionFour?:()=>Promise<M04Service>;subscribe?:(callback:()=>void)=>()=>void;audio?:BunkerAudioController};
type Props={eventSlug?:string;dependencies?:BunkerScreenGuardDependencies;children:ReactNode};
function browserDependencies(eventSlug:string):BunkerScreenGuardDependencies|null{try{const client=getSupabaseClient();const rpc=client as unknown as BunkerRpcClient&MissionOneRpcClient;const realtime=client as unknown as BunkerRealtimeClient;return{load:()=>getBunkerScreenState(rpc,eventSlug),loadMissionOne:()=>getMissionOneScreenReadModel(rpc,eventSlug),loadMissionTwo:()=>getMissionTwoScreenReadModel(rpc,eventSlug),loadMissionThree:()=>getMissionThreeScreenReadModel(rpc,eventSlug),loadMissionFour:()=>getMissionFourScreenReadModel(rpc,eventSlug),subscribe:(cb)=>subscribeToBunkerRefresh(realtime,eventSlug,cb),audio:createBunkerAudioController()};}catch{return null;}}
type Timed<T>={model:T;receivedAt:number};
function projectedRemaining(deadlineAt:string,serverNow:string,receivedAt:number,nowMs:number){const initial=(Date.parse(deadlineAt)-Date.parse(serverNow))/1000;return Math.max(0,Math.ceil(initial-(nowMs-receivedAt)/1000));}
function m01Model(value:Timed<Extract<M01Service,{status:'active'}>>|null,now:number):MissionOneScreenReadModel|undefined{return value?{title:value.model.title,publicSummary:value.model.publicSummary,remainingSeconds:projectedRemaining(value.model.deadlineAt,value.model.serverNow,value.receivedAt,now),wagons:value.model.wagons}:undefined;}
function m02Model(value:Timed<Extract<M02Service,{status:'active'|'completed'}>>|null,now:number):MissionTwoScreenModel|undefined{return value?{title:value.model.title,subtitle:value.model.subtitle,remainingSeconds:projectedRemaining(value.model.deadlineAt,value.model.serverNow,value.receivedAt,now),wagons:value.model.wagons}:undefined;}
function m03Model(value:Timed<Extract<M03Service,{status:'active'|'completed'}>>|null,now:number):MissionThreeScreenModel|undefined{return value?{title:value.model.title,remainingSeconds:projectedRemaining(value.model.deadlineAt,value.model.serverNow,value.receivedAt,now),wagons:value.model.wagons}:undefined;}
function m04Model(value:Timed<Extract<M04Service,{status:'active'|'completed'}>>|null,now:number):MissionFourScreenModel|undefined{return value?{title:value.model.title,remainingSeconds:projectedRemaining(value.model.deadlineAt,value.model.serverNow,value.receivedAt,now),groups:value.model.groups}:undefined;}
function remainingFromState(state:Extract<BunkerScreenState,{status:'active'}>,now:number,offset:number){const started=Date.parse(state.startedAt);if(!Number.isFinite(started))return state.remainingSeconds;return Math.max(0,Math.ceil(state.durationSeconds-(now+offset-started)/1000));}

export function BunkerScreenGuard({eventSlug='liza-viktor',dependencies,children}:Props){
 const[browserDeps,setBrowserDeps]=useState<BunkerScreenGuardDependencies|null>(null),deps=dependencies??browserDeps;const[state,setState]=useState<BunkerScreenState|null>(null);const[m1,setM1]=useState<Timed<Extract<M01Service,{status:'active'}>>|null>(null);const[m2,setM2]=useState<Timed<Extract<M02Service,{status:'active'|'completed'}>>|null>(null);const[m3,setM3]=useState<Timed<Extract<M03Service,{status:'active'|'completed'}>>|null>(null);const[m4,setM4]=useState<Timed<Extract<M04Service,{status:'active'|'completed'}>>|null>(null);const[contractVersion,setContractVersion]=useState<1|2|null>(null);const[nowMs,setNowMs]=useState(()=>Date.now());const[motionPreference,setMotionPreference]=useState<'full'|'reduced'>(()=>typeof window!=='undefined'&&typeof window.matchMedia==='function'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches?'reduced':'full');const serverOffsetRef=useRef(0),latestServerMsRef=useRef(Number.NEGATIVE_INFINITY),previousUnlockRef=useRef<boolean|null>(null);
 const applyServerState=(next:BunkerScreenState)=>{const received=Date.now(),serverMs=Date.parse(next.serverNow);if(Number.isFinite(serverMs)&&serverMs<latestServerMsRef.current)return false;if(Number.isFinite(serverMs))latestServerMsRef.current=serverMs;serverOffsetRef.current=Number.isFinite(serverMs)?serverMs-received:0;setState(next);setNowMs(received);return true;};
 useEffect(()=>{if(dependencies){setBrowserDeps(null);return;}const next=browserDependencies(eventSlug);setBrowserDeps(next);return()=>next?.audio?.dispose();},[dependencies,eventSlug]);
 useEffect(()=>{if(typeof window.matchMedia!=='function')return;const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotionPreference(query.matches?'reduced':'full');update();query.addEventListener?.('change',update);return()=>query.removeEventListener?.('change',update);},[]);
 const apply=<T extends {contractVersion:1|2;status:string}>(next:T|null,set:(value:any)=>void)=>{if(!next)return;setContractVersion(next.contractVersion);set(next.status==='active'||next.status==='completed'?{model:next,receivedAt:Date.now()}:null);};
 const refresh=()=>{if(!deps)return;void deps.load().then(applyServerState).catch(()=>{});void Promise.resolve(deps.loadMissionOne?.()??null).then(next=>apply(next,setM1)).catch(()=>{});void Promise.resolve(deps.loadMissionTwo?.()??null).then(next=>apply(next,setM2)).catch(()=>{});void Promise.resolve(deps.loadMissionThree?.()??null).then(next=>apply(next,setM3)).catch(()=>{});void Promise.resolve(deps.loadMissionFour?.()??null).then(next=>apply(next,setM4)).catch(()=>{});};const refreshRef=useRef(refresh);refreshRef.current=refresh;
 useEffect(()=>{if(!deps)return;const reload=()=>refreshRef.current();reload();const unsubscribe=deps.subscribe?.(reload);window.addEventListener('focus',reload);window.addEventListener('online',reload);return()=>{unsubscribe?.();window.removeEventListener('focus',reload);window.removeEventListener('online',reload);};},[deps]);
 const remainingSeconds=state?.status==='active'?remainingFromState(state,nowMs,serverOffsetRef.current):0,bunkerActive=state?.status==='active',activePhase=state?.status==='active'?phaseForGlobalGameState(state.globalGameState,state.phase??'emergency'):null,emergencyPhase=bunkerActive&&activePhase==='emergency';
 useEffect(()=>{setBunkerPresentationProtected(bunkerActive);return()=>setBunkerPresentationProtected(false);},[bunkerActive]);useEffect(()=>{if(!bunkerActive||remainingSeconds<=0)return;const interval=window.setInterval(()=>setNowMs(Date.now()),250);return()=>window.clearInterval(interval);},[bunkerActive,remainingSeconds<=0]);useEffect(()=>{if(!deps)return;const interval=window.setInterval(()=>refreshRef.current(),bunkerActive?2000:1500);return()=>window.clearInterval(interval);},[deps,bunkerActive]);
 useEffect(()=>{const audio=deps?.audio;if(!audio)return;if(!emergencyPhase||remainingSeconds<=0||state?.status!=='active'||!state.soundEnabled){audio.stopAlarm();return;}audio.startAlarm();void audio.arm();return()=>audio.stopAlarm();},[deps,emergencyPhase,remainingSeconds<=0,state?.status==='active'?state.soundEnabled:false]);useEffect(()=>{const audio=deps?.audio;if(!audio)return;if(!bunkerActive||state?.status!=='active'||!state.soundEnabled){audio.stopAmbience();return;}audio.startAmbience();void audio.arm();return()=>audio.stopAmbience();},[deps,bunkerActive,state?.status==='active'?state.soundEnabled:false]);useEffect(()=>{const audio=deps?.audio;if(!bunkerActive||state?.status!=='active'){previousUnlockRef.current=null;return;}const final=activePhase==='final'||activePhase==='completed',was=previousUnlockRef.current;if(final&&state.soundEnabled&&was===false&&state.unlocked){audio?.playDoorUnlock();void audio?.arm();}previousUnlockRef.current=state.unlocked;},[deps,bunkerActive,activePhase,state?.status==='active'?state.unlocked:false,state?.status==='active'?state.soundEnabled:false]);
 return<>{children}{bunkerActive&&state?.status==='active'&&activePhase==='emergency'&&<BunkerEmergencyScene remainingSeconds={remainingSeconds} motionPreference={motionPreference}/>} {bunkerActive&&state?.status==='active'&&activePhase!=='emergency'&&<BunkerQuestScene key={state.globalGameState??activePhase} state={state} remainingSeconds={remainingSeconds} motionPreference={motionPreference} missionOne={m01Model(m1,nowMs)} missionTwo={m02Model(m2,nowMs)} missionThree={m03Model(m3,nowMs)} missionFour={m04Model(m4,nowMs)} bunkerContractVersion={contractVersion??undefined}/>}</>;
}
