import { useState } from 'react';
import type { ActiveGuestBunkerRuntime } from './bunkerRuntime.service';
import { BunkerResponsivePicture, type BunkerAsset } from './BunkerResponsivePicture';
import type { BunkerV2ActiveGuestRuntime } from './v2/contracts';
import { bunkerArchiveLabel,bunkerContentTypeLabel,bunkerItemLabel,bunkerStageLabel,bunkerStatusLabel } from './v2/labels';
import { MissionOnePlayer,type MissionOnePlayerReadModel } from './v2/MissionOnePlayer';
import { MissionTwoPlayer,type MissionTwoPlayerReadModel } from './v2/MissionTwoPlayer';
import { MissionThreePlayer,type MissionThreePlayerReadModel } from './v2/MissionThreePlayer';
import { MissionFourPlayer,type MissionFourPlayerReadModel } from './v2/MissionFourPlayer';
const SECTIONS=['МОЙ ВАГОН','ПЕРСОНАЖ','ПАССАЖИРЫ','ИНВЕНТАРЬ','АРХИВ','СОСТОЯНИЕ','ТЕКУЩЕЕ ЗАДАНИЕ']as const;type Section=typeof SECTIONS[number];
function rows(value:unknown[]):Record<string,unknown>[]{return value.filter((entry):entry is Record<string,unknown>=>typeof entry==='object'&&entry!==null&&!Array.isArray(entry));}
type ArchiveEntry={artifactKey:string;contentType:string;decryptionStatus:string;scope:string};function nonEmptyText(value:unknown):string|null{return typeof value==='string'&&value.trim()?value:null;}function archiveEntries(value:unknown[]):ArchiveEntry[]{return rows(value).flatMap((entry)=>{const artifactKey=nonEmptyText(entry.artifactKey),contentType=nonEmptyText(entry.contentType),decryptionStatus=nonEmptyText(entry.decryptionStatus),scope=nonEmptyText(entry.scope);return artifactKey&&contentType&&decryptionStatus&&scope?[{artifactKey,contentType,decryptionStatus,scope}]:[];});}
function archiveArtwork(entry:ArchiveEntry):BunkerAsset|null{const key=entry.artifactKey.toLocaleLowerCase('en-US'),type=entry.contentType.toLocaleLowerCase('en-US');if(key.includes('bk17')||key.includes('bk-17'))return'archive-bk17';if(type==='card'||key.includes('card'))return'archive-card';if(type==='document'||key.includes('document'))return'archive-document';return null;}
type Props={runtime:ActiveGuestBunkerRuntime|BunkerV2ActiveGuestRuntime;connectionError?:string;missionOne?:MissionOnePlayerReadModel;missionTwo?:MissionTwoPlayerReadModel;missionThree?:MissionThreePlayerReadModel;missionFour?:MissionFourPlayerReadModel;onConfirmMissionOne?:(ids:string[])=>Promise<void>|void;onSubmitMissionTwo?:(answers:string[])=>Promise<void>|void;onUseMissionTwoAbility?:(ability:'system_access'|'terminal_hack')=>Promise<void>|void;onConfirmMissionThree?:(problems:string[])=>Promise<void>|void;onUseMissionThreeAbility?:(problemKey:string)=>Promise<void>|void;onSendMissionFourMessage?:(message:string)=>Promise<void>|void;onProposeMissionFourTrade?:(input:{targetWagonNumber:number;itemKey:string;quantity:number})=>Promise<void>|void;onRespondMissionFourTrade?:(id:string,response:'accept'|'reject')=>Promise<void>|void;onSubmitMissionFourAnswer?:(answer:string)=>Promise<void>|void};
export function BunkerPlayerDashboard({runtime,connectionError='',missionOne,missionTwo,missionThree,missionFour,onConfirmMissionOne,onSubmitMissionTwo,onUseMissionTwoAbility,onConfirmMissionThree,onUseMissionThreeAbility,onSendMissionFourMessage,onProposeMissionFourTrade,onRespondMissionFourTrade,onSubmitMissionFourAnswer}:Props){
 const isV2='contractVersion'in runtime;const guest=isV2?{...runtime.viewer.guest,joinedLate:runtime.character.m01Eligibility==='late_joiner'}:runtime.guest;const activeId=missionOne?.instanceId??missionTwo?.instanceId??missionThree?.instanceId??missionFour?.instanceId??'';const wagon=isV2?{id:activeId,...runtime.viewer.wagon}:runtime.wagon;const gameState=isV2?runtime.state:runtime.game.state;const v2Passengers=missionOne?.members.map(member=>({...member,hiddenTraitRevealed:false}))??[];const hasMission=Boolean(missionOne||missionTwo||missionThree||missionFour);const[section,setSection]=useState<Section>(hasMission?'ТЕКУЩЕЕ ЗАДАНИЕ':'МОЙ ВАГОН');const inventory=rows(isV2?(missionThree?.inventory??missionFour?.inventory??[]):runtime.inventory);const passengers=rows(isV2?v2Passengers:runtime.passengers);const archive=archiveEntries(isV2?[]:runtime.archive);const mission=isV2?runtime.currentMission:null;
 return <section className={`bunker-player-dashboard${hasMission?' bunker-player-dashboard--active-mission':''}`} aria-label="Игровой модуль Бункер">
  {missionOne&&<MissionOnePlayer model={missionOne} onConfirm={onConfirmMissionOne}/>} {missionTwo&&<MissionTwoPlayer model={missionTwo} onSubmit={onSubmitMissionTwo} onUseAbility={onUseMissionTwoAbility}/>} {missionThree&&<MissionThreePlayer model={missionThree} onConfirm={onConfirmMissionThree} onUseAbility={onUseMissionThreeAbility}/>} {missionFour&&<MissionFourPlayer model={missionFour} onSend={onSendMissionFourMessage} onProposeTrade={onProposeMissionFourTrade} onRespondTrade={onRespondMissionFourTrade} onAnswer={onSubmitMissionFourAnswer}/>} 
  <header className="bunker-player-dashboard__header"><div><p className="bunker-player-dashboard__index">ПОСЛЕДНИЙ ВАГОН · {wagon.label}</p><h2 className="bunker-player-dashboard__guest-name">{guest.realName.toLocaleUpperCase('ru-RU')}</h2></div><span className="bunker-player-dashboard__state">{bunkerStageLabel(gameState).toLocaleUpperCase('ru-RU')}</span></header>
  {!hasMission&&<BunkerResponsivePicture asset="tunnel-relief-wide" mobileAsset="tunnel-relief-mobile" className="bunker-player-dashboard__relief" testId="bunker-tunnel-relief" sizes="(max-width: 640px) calc(100vw - 1.3rem), min(72rem, calc(100vw - 5rem))" loading="eager"/>}
  {connectionError&&<p className="bunker-player-dashboard__connection" role="alert">{connectionError}</p>}{guest.joinedLate&&<p className="bunker-player-dashboard__late" role="status">Вы присоединились после отправления. Некоторые решения уже приняты вашим вагоном — это нормально, вы продолжаете играть.</p>}{runtime.character.status==='excluded'&&<p className="bunker-player-dashboard__continuity" role="status">Персонаж исключён из истории, но вы продолжаете участвовать: обсуждайте решения вагона и выполняйте задания.</p>}{runtime.character.status==='saved'&&<p className="bunker-player-dashboard__continuity" role="status">Персонаж спасён. Вы продолжаете участвовать во всех следующих заданиях.</p>}
  {mission&&!hasMission&&<button className="bunker-player-dashboard__primary-action" type="button" onClick={()=>setSection('ТЕКУЩЕЕ ЗАДАНИЕ')}>ОТКРЫТЬ ТЕКУЩЕЕ ЗАДАНИЕ</button>}
  <nav className="bunker-player-dashboard__nav" aria-label="Разделы игры">{SECTIONS.map(item=><button key={item} type="button" aria-pressed={section===item} onClick={()=>setSection(item)}>{item}</button>)}</nav><div className="bunker-player-dashboard__content">
  {section==='МОЙ ВАГОН'&&<article><p className="bunker-player-dashboard__index">СОСТАВ</p><h3>{wagon.label.toLocaleUpperCase('ru-RU')}</h3><p>{passengers.length} пассажиров · решения команды синхронизируются автоматически.</p></article>}
  {section==='ПЕРСОНАЖ'&&<article className="bunker-player-character"><p className="bunker-player-dashboard__index">ВАША РОЛЬ</p><h3>{runtime.character.profession}</h3><dl><div><dt>Здоровье</dt><dd>{runtime.character.health}</dd></div><div><dt>Навык</dt><dd>{runtime.character.visibleSkill}</dd></div><div><dt>Скрытая характеристика</dt><dd>{'hiddenTrait'in runtime.character?(runtime.character.hiddenTrait??'ПОКА СКРЫТО'):'ПОКА СКРЫТО'}</dd></div></dl><div className="bunker-player-character__ability"><span>ОСОБАЯ СПОСОБНОСТЬ</span><p>{runtime.character.abilityDescription}</p><small>Когда способность можно будет применить, система покажет отдельную понятную кнопку.</small></div></article>}
  {section==='ПАССАЖИРЫ'&&<div className="bunker-player-list">{passengers.length===0?<article><h3>СОСТАВ ВАГОНА</h3><p>Список пассажиров появится здесь после синхронизации.</p></article>:passengers.map(p=><article key={String(p.guestId)}><h3>{String(p.realName)}</h3><strong>{String(p.profession)}</strong><p>{String(p.visibleSkill)}</p><small>{p.hiddenTraitRevealed?String(p.hiddenTrait):'СКРЫТАЯ ХАРАКТЕРИСТИКА · ПОКА НЕИЗВЕСТНА'}</small></article>)}</div>}
  {section==='ИНВЕНТАРЬ'&&<div className="bunker-player-list">{inventory.length===0?<article><h3>ИНВЕНТАРЬ ПОКА ПУСТ</h3><p>Предметы появятся здесь, когда вагон получит аварийный запас.</p></article>:inventory.map((item,index)=><article key={`${String(item.itemKey)}:${index}`}><h3>{bunkerItemLabel(String(item.itemKey)).toLocaleUpperCase('ru-RU')}</h3>{item.status&&<strong>{bunkerStatusLabel(String(item.status)).toLocaleUpperCase('ru-RU')}</strong>}<p>Количество: {String(item.quantity)}</p></article>)}</div>}
  {section==='АРХИВ'&&<article aria-label="Архив вагона"><h3>АРХИВ ВАГОНА</h3>{archive.length===0?<p>Архив пока пуст. Найденные материалы появятся здесь автоматически.</p>:<div className="bunker-player-list">{archive.map(entry=>{const artwork=archiveArtwork(entry),label=bunkerArchiveLabel(entry.artifactKey);return<article key={`${entry.scope}:${entry.artifactKey}`}>{artwork&&<BunkerResponsivePicture asset={artwork} className="bunker-player-archive__artwork" testId="bunker-archive-artwork" sizes="(max-width: 760px) calc(100vw - 3.3rem), 24rem"/>}<h3>{label.title.toLocaleUpperCase('ru-RU')}</h3><strong>{bunkerContentTypeLabel(entry.contentType)}</strong><p>{bunkerStatusLabel(entry.decryptionStatus)}</p><small>{bunkerStatusLabel(entry.scope)}</small><p>{label.hint}</p></article>;})}</div>}</article>}
  {section==='СОСТОЯНИЕ'&&(isV2?<article><h3>СОСТОЯНИЕ ВАГОНА</h3><p>Состояние систем меняется от решений команды и сохраняется на сервере.</p></article>:<article><h3>СОСТОЯНИЕ ВАГОНА</h3><p>ПИТАНИЕ · {bunkerStatusLabel(String(runtime.wagonState.powerStatus)).toLocaleUpperCase('ru-RU')}</p><p>СВЯЗЬ · {bunkerStatusLabel(String(runtime.wagonState.communicationStatus)).toLocaleUpperCase('ru-RU')}</p><p>НАВИГАЦИЯ · {bunkerStatusLabel(String(runtime.wagonState.navigationStatus)).toLocaleUpperCase('ru-RU')}</p></article>)}
  {section==='ТЕКУЩЕЕ ЗАДАНИЕ'&&<article aria-label="Текущее задание"><h3>ТЕКУЩЕЕ ЗАДАНИЕ</h3>{hasMission?<p>Активное задание находится в верхней части экрана. После решения вы сможете продолжить пользоваться всеми разделами.</p>:<><dl className="bunker-player-mission-meta"><div><dt>Сейчас</dt><dd>{bunkerStageLabel(gameState)}</dd></div>{mission&&<div><dt>Что делать</dt><dd>Следуйте инструкции текущего этапа. Если действие доступно лично вам, появится отдельная кнопка.</dd></div>}</dl>{!mission&&<p>Сейчас активного задания нет. Оставайтесь на связи с вашим вагоном.</p>}</>}</article>}
  </div></section>;
}
