-- Owner-only rehearsal tools. Every mutation except seeding/reset is hard-gated by bunker_state.game_mode='test'.

create or replace function public._require_bunker_v2_test_mode(p_event_id uuid)
returns uuid language plpgsql security definer set search_path='' as $$ declare v_state public.bunker_state%rowtype;begin perform public._require_bunker_owner(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id for update;if v_state.run_nonce is null or v_state.game_mode<>'test' then raise exception 'Bunker rehearsal mode required' using errcode='55000';end if;return v_state.run_nonce;end;$$;
revoke all on function public._require_bunker_v2_test_mode(uuid) from public,anon,authenticated;

create or replace function public.owner_bunker_v2_seed_test_guests(p_event_id uuid,p_count integer)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event public.events%rowtype;v_state public.bunker_state%rowtype;v_real integer;v_wagons integer;v_i integer;v_carriage uuid;v_seq bigint;begin perform public._require_bunker_owner(p_event_id);if p_count<15 or p_count>40 then raise exception 'test guest count must be 15..40' using errcode='22023';end if;select e.* into v_event from public.events e where e.id=p_event_id for update;select s.* into v_state from public.bunker_state s where s.event_id=p_event_id for update;if v_state.run_nonce is not null then raise exception 'reset Bunker progress before reseeding rehearsal guests' using errcode='55000';end if;select count(*)::integer into v_real from public.guests g where g.event_id=p_event_id and coalesce(g.affiliation_detail,'')<>'__BUNKER_TEST__';if v_real>0 then raise exception 'real registrations exist; synthetic rehearsal seeding is blocked to protect them' using errcode='55000';end if;delete from public.guests g where g.event_id=p_event_id and g.affiliation_detail='__BUNKER_TEST__';v_wagons:=case when p_count<=18 then 2 when p_count<=26 then 3 when p_count<=36 then 4 else 5 end;update public.carriages set enabled=number<=v_wagons where event_id=p_event_id;v_seq:=1;for v_i in 1..p_count loop select c.id into v_carriage from public.carriages c where c.event_id=p_event_id and c.number=1+mod(v_i-1,v_wagons);insert into public.guests(event_id,first_name,last_name,affiliation_type,affiliation_detail,carriage_id,ticket_sequence,ticket_number) values(p_event_id,'Тест '||lpad(v_i::text,2,'0'),'Пассажир','common','__BUNKER_TEST__',v_carriage,v_seq,'TST-'||lpad(v_i::text,3,'0'));v_seq:=v_seq+1;end loop;update public.events set composition_locked=true,registration_open=true,next_ticket_sequence=v_seq where id=p_event_id;insert into public.owner_action_log(event_id,owner_user_id,action,payload) values(p_event_id,auth.uid(),'bunker_test_guests_seeded',jsonb_build_object('guestCount',p_count,'wagonCount',v_wagons));return jsonb_build_object('status','seeded','guestCount',p_count,'wagonCount',v_wagons);end;$$;
revoke all on function public.owner_bunker_v2_seed_test_guests(uuid,integer) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_seed_test_guests(uuid,integer) to authenticated;

create or replace function public.owner_prepare_bunker_v2_test(p_event_id uuid,p_command_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_result jsonb;v_run uuid;begin perform public._require_bunker_owner(p_event_id);v_result:=public.owner_prepare_bunker_v2(p_event_id,p_command_id);select s.run_nonce into v_run from public.bunker_state s where s.event_id=p_event_id for update;update public.bunker_state set game_mode='test',updated_at=now() where event_id=p_event_id;insert into public.owner_action_log(event_id,owner_user_id,action,payload) values(p_event_id,auth.uid(),'bunker_test_run_prepared',jsonb_build_object('runNonce',v_run));return v_result||jsonb_build_object('gameMode','test');end;$$;
revoke all on function public.owner_prepare_bunker_v2_test(uuid,uuid) from public,anon,authenticated;grant execute on function public.owner_prepare_bunker_v2_test(uuid,uuid) to authenticated;

create or replace function public.owner_bunker_v2_test_accelerate(p_event_id uuid,p_seconds integer)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_run uuid;v_state public.bunker_state%rowtype;v_changed integer:=0;begin if p_seconds<1 or p_seconds>600 then raise exception 'test acceleration must be 1..600 seconds' using errcode='22023';end if;v_run:=public._require_bunker_v2_test_mode(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id;update public.bunker_mission_instances i set deadline_at=greatest(clock_timestamp()+interval '1 second',coalesce(i.deadline_at,clock_timestamp())-make_interval(secs=>p_seconds)) where i.event_id=p_event_id and i.run_nonce=v_run and i.mission_code=v_state.global_game_state and i.status='active';get diagnostics v_changed=row_count;if v_state.global_game_state='FINAL_30' then update public.bunker_state set final_started_at=coalesce(final_started_at,clock_timestamp())-make_interval(secs=>p_seconds),updated_at=now() where event_id=p_event_id;end if;return jsonb_build_object('status','accelerated','seconds',p_seconds,'instances',v_changed);end;$$;
revoke all on function public.owner_bunker_v2_test_accelerate(uuid,integer) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_test_accelerate(uuid,integer) to authenticated;

create or replace function public.owner_bunker_v2_test_simulate_current(p_event_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_run uuid;v_state public.bunker_state%rowtype;v_instance public.bunker_mission_instances%rowtype;v_outcome jsonb;v_number integer;v_count integer:=0;v_now timestamptz:=clock_timestamp();begin v_run:=public._require_bunker_v2_test_mode(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id for update;if v_state.global_game_state='FINAL_30' then perform public.owner_bunker_v2_emergency_open(p_event_id);return jsonb_build_object('status','simulated','state','FINAL_30','opened',true);end if;if v_state.global_game_state not in ('MISSION_01','MISSION_02','MISSION_03','MISSION_04','MISSION_05','MISSION_06') then return jsonb_build_object('status','nothing_to_simulate','state',v_state.global_game_state);end if;for v_instance in select i.* from public.bunker_mission_instances i where i.event_id=p_event_id and i.run_nonce=v_run and i.mission_code=v_state.global_game_state and i.status in ('planned','active') order by i.id for update loop v_outcome:=jsonb_build_object('status','test_simulated');if v_state.global_game_state='MISSION_05' then select c.number into v_number from public.carriages c where c.id::text=v_instance.scope_key;v_outcome:=public._bunker_v2_apply_m05_outcome(p_event_id,v_run,v_instance.scope_key::uuid,case when mod(v_number,2)=1 then 'A' else 'B' end,true);elsif v_state.global_game_state='MISSION_06' then v_outcome:=jsonb_build_object('status','success','protocol','B','sector','04','accessCode','4719','testSimulated',true);update public.bunker_final_parameters set status='resolved',source_kind='test_simulation',source_instance_id=v_instance.id,resolved_at=coalesce(resolved_at,v_now) where event_id=p_event_id and run_nonce=v_run and parameter_key in ('sector','access_code');end if;update public.bunker_mission_instances set status='completed',started_at=coalesce(started_at,v_now),completed_at=v_now,outcome=coalesce(outcome,'{}'::jsonb)||v_outcome where id=v_instance.id;update public.bunker_mission_members set member_status='completed',updated_at=v_now where instance_id=v_instance.id;v_count:=v_count+1;end loop;return jsonb_build_object('status','simulated','state',v_state.global_game_state,'instances',v_count);end;$$;
revoke all on function public.owner_bunker_v2_test_simulate_current(uuid) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_test_simulate_current(uuid) to authenticated;

create or replace function public.owner_bunker_v2_test_set_inventory(p_event_id uuid,p_wagon_number integer,p_item_key text,p_quantity integer)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_run uuid;v_carriage uuid;begin v_run:=public._require_bunker_v2_test_mode(p_event_id);if p_wagon_number not between 1 and 5 or p_item_key not in ('medkit','radio','generator','tools','water','gas_mask') or p_quantity<0 or p_quantity>9 then raise exception 'invalid test inventory values' using errcode='22023';end if;select c.id into v_carriage from public.carriages c where c.event_id=p_event_id and c.number=p_wagon_number;if v_carriage is null then raise exception 'wagon not found' using errcode='P0002';end if;delete from public.bunker_inventory_transfers t using public.bunker_inventory_lots l where t.source_lot_id=l.id and t.event_id=p_event_id and t.run_nonce=v_run and t.status='proposed' and l.carriage_id=v_carriage and l.item_key=p_item_key;delete from public.bunker_inventory_lots l where l.event_id=p_event_id and l.run_nonce=v_run and l.carriage_id=v_carriage and l.item_key=p_item_key and l.status='available';if p_quantity>0 then insert into public.bunker_inventory_lots(event_id,run_nonce,carriage_id,item_key,quantity,status,metadata) values(p_event_id,v_run,v_carriage,p_item_key,p_quantity,'available',jsonb_build_object('testOverride',true));end if;return jsonb_build_object('status','updated','wagonNumber',p_wagon_number,'itemKey',p_item_key,'quantity',p_quantity);end;$$;
revoke all on function public.owner_bunker_v2_test_set_inventory(uuid,integer,text,integer) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_test_set_inventory(uuid,integer,text,integer) to authenticated;

create or replace function public.owner_bunker_v2_test_set_wagon_state(p_event_id uuid,p_wagon_number integer,p_power text,p_communication text,p_navigation text)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_run uuid;v_carriage uuid;begin v_run:=public._require_bunker_v2_test_mode(p_event_id);if p_power not in ('stable','unstable','offline') or p_communication not in ('working','degraded','offline') or p_navigation not in ('working','degraded','offline') then raise exception 'invalid test wagon state' using errcode='22023';end if;select c.id into v_carriage from public.carriages c where c.event_id=p_event_id and c.number=p_wagon_number;if v_carriage is null then raise exception 'wagon not found' using errcode='P0002';end if;update public.bunker_wagon_state set power_status=p_power,communication_status=p_communication,navigation_status=p_navigation,updated_at=now() where event_id=p_event_id and run_nonce=v_run and carriage_id=v_carriage;if not found then raise exception 'test wagon state missing' using errcode='P0002';end if;return jsonb_build_object('status','updated','wagonNumber',p_wagon_number);end;$$;
revoke all on function public.owner_bunker_v2_test_set_wagon_state(uuid,integer,text,text,text) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_test_set_wagon_state(uuid,integer,text,text,text) to authenticated;

create or replace function public.owner_bunker_v2_reset_game_and_registrations(p_event_id uuid,p_confirmation text)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v_deleted integer;begin perform public._require_bunker_owner(p_event_id);if coalesce(p_confirmation,'')<>'СБРОСИТЬ ИГРУ И РЕГИСТРАЦИИ' then raise exception 'explicit game and registration reset confirmation required' using errcode='22023';end if;perform public.owner_reset_bunker_progress(p_event_id,gen_random_uuid());delete from public.guests g where g.event_id=p_event_id;get diagnostics v_deleted=row_count;update public.carriages set enabled=true where event_id=p_event_id;update public.events set registration_open=true,composition_locked=false,next_ticket_sequence=1 where id=p_event_id;insert into public.owner_action_log(event_id,owner_user_id,action,payload) values(p_event_id,auth.uid(),'bunker_game_and_registrations_reset',jsonb_build_object('deletedGuests',v_deleted));return jsonb_build_object('status','reset','deletedGuests',v_deleted,'preservedCoupleAnswers',true);end;$$;
revoke all on function public.owner_bunker_v2_reset_game_and_registrations(uuid,text) from public,anon,authenticated;grant execute on function public.owner_bunker_v2_reset_game_and_registrations(uuid,text) to authenticated;
