-- M06 «Общий протокол». Each wagon owns a private fragment; only server consensus unlocks final data.
create or replace function public._bunker_v2_m06_correct_protocol()
returns text language sql immutable security definer set search_path='' as $$ select 'B'::text; $$;
revoke all on function public._bunker_v2_m06_correct_protocol() from public,anon,authenticated;

create or replace function public._bunker_v2_m06_fragment(p_index integer,p_total integer)
returns jsonb language plpgsql immutable security definer set search_path='' as $$
begin
 if p_total=2 then
  return case p_index when 1 then jsonb_build_object('key','protocol_fragment_1','label','Фрагмент вагона 01','body','Архив BK-17: в резервной схеме дважды повторяется обозначение TUNNEL B.') else jsonb_build_object('key','protocol_fragment_2','label','Фрагмент вагона 02','body','Безопасная точка отмечена как SECTOR 04. Код допуска восстановлен как 4719.') end;
 elsif p_total=3 then
  return case p_index when 1 then jsonb_build_object('key','protocol_fragment_1','label','Фрагмент вагона 01','body','Маршрутный архив: служебная ветка обозначена TUNNEL B.') when 2 then jsonb_build_object('key','protocol_fragment_2','label','Фрагмент вагона 02','body','Карта защищённого объекта: безопасная точка находится в SECTOR 04.') else jsonb_build_object('key','protocol_fragment_3','label','Фрагмент вагона 03','body','Контроль доступа: подтверждён код 4719.') end;
 else
  return case p_index when 1 then jsonb_build_object('key','protocol_fragment_1','label','Фрагмент вагона 01','body','Маршрутный архив: служебная ветка обозначена TUNNEL B.') when 2 then jsonb_build_object('key','protocol_fragment_2','label','Фрагмент вагона 02','body','Карта защищённого объекта: безопасная точка находится в SECTOR 04.') when 3 then jsonb_build_object('key','protocol_fragment_3','label','Фрагмент вагона 03','body','Первая половина кода доступа: 47••.') when 4 then jsonb_build_object('key','protocol_fragment_4','label','Фрагмент вагона 04','body','Вторая половина кода доступа: ••19.') else jsonb_build_object('key','protocol_fragment_5','label','Фрагмент вагона 05','body','Контрольная запись BK-17 связывает маршрут, сектор и код в один общий протокол.') end;
 end if;
end;$$;
revoke all on function public._bunker_v2_m06_fragment(integer,integer) from public,anon,authenticated;

create or replace function public._bunker_v2_m06_definition() returns jsonb language sql immutable security definer set search_path='' as $$
 select jsonb_build_object('title','Общий протокол','intro','У каждого вагона свой фрагмент. Передайте его в общий протокол, сравните данные и согласуйте один вариант всем составом.','options',jsonb_build_array(jsonb_build_object('key','A','title','Протокол A','summary','TUNNEL A · SECTOR 03'),jsonb_build_object('key','B','title','Протокол B','summary','TUNNEL B · SECTOR 04'),jsonb_build_object('key','C','title','Протокол C','summary','SERVICE SHAFT · SECTOR 05')));
$$;
revoke all on function public._bunker_v2_m06_definition() from public,anon,authenticated;
update public.bunker_mission_instances set definition=definition||public._bunker_v2_m06_definition() where mission_code='MISSION_06' and definition->>'contractVersion'='2';
create or replace function public._bunker_v2_enrich_m06_instance() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.mission_code='MISSION_06' and new.definition->>'contractVersion'='2' then new.definition:=new.definition||public._bunker_v2_m06_definition();end if;return new;end;$$;
revoke all on function public._bunker_v2_enrich_m06_instance() from public,anon,authenticated;drop trigger if exists bunker_v2_enrich_m06_before_insert on public.bunker_mission_instances;create trigger bunker_v2_enrich_m06_before_insert before insert on public.bunker_mission_instances for each row execute function public._bunker_v2_enrich_m06_instance();

create or replace function public._bunker_v2_m06_consensus(p_instance_id uuid)
returns jsonb language sql stable security definer set search_path='' as $$
 with member_vote as (
  select m.carriage_id,c.label,m.guest_id,d.payload->>'vote' vote
  from public.bunker_mission_members m join public.carriages c on c.id=m.carriage_id
  left join public.bunker_mission_decisions d on d.instance_id=m.instance_id and d.decision_key='m06_vote' and d.actor_kind='guest' and d.actor_id=m.guest_id and d.status='confirmed'
  where m.instance_id=p_instance_id
 ), counts as (
  select carriage_id,max(label) label,count(*) filter(where vote='A')::integer votes_a,count(*) filter(where vote='B')::integer votes_b,count(*) filter(where vote='C')::integer votes_c,(floor(count(*)/2.0)::integer+1) required
  from member_vote group by carriage_id
 )
 select coalesce(jsonb_agg(jsonb_build_object('wagonId',carriage_id,'label',label,'votesA',votes_a,'votesB',votes_b,'votesC',votes_c,'required',required,'consensus',case when votes_a>=required then 'A' when votes_b>=required then 'B' when votes_c>=required then 'C' else null end) order by label),'[]'::jsonb) from counts;
$$;
revoke all on function public._bunker_v2_m06_consensus(uuid) from public,anon,authenticated;

create or replace function public._submit_bunker_command_m06(p_event_slug text,p_device_key text,p_command_id uuid,p_command_type text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest public.guests%rowtype;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_member public.bunker_mission_members%rowtype;v_profile public.bunker_guest_profiles%rowtype;v_existing public.bunker_command_receipts%rowtype;v_hash text;v_fragment jsonb;v_expected_key text;v_vote text;v_consensus jsonb;v_total integer;v_ready integer;v_distinct integer;v_global text;v_entry_sector uuid;v_entry_code uuid;v_hint text;v_result jsonb;v_now timestamptz:=clock_timestamp();
begin
 if p_command_id is null or p_payload is null or jsonb_typeof(p_payload)<>'object' then raise exception 'invalid M06 command' using errcode='22023';end if;
 select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then raise exception 'Bunker event not found' using errcode='P0002';end if;select g.* into v_guest from public.guests g where g.event_id=v_event_id and g.id=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest.id is null then raise exception 'registered Bunker guest required' using errcode='42501';end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id for update;if v_state.run_nonce is null then raise exception 'active Bunker V2 run required' using errcode='55000';end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then raise exception 'active Bunker V2 run required' using errcode='55000';end if;v_hash:=encode(extensions.digest(convert_to(jsonb_build_object('commandType',p_command_type,'payload',p_payload)::text,'UTF8'),'sha256'),'hex');select r.* into v_existing from public.bunker_command_receipts r where r.run_nonce=v_state.run_nonce and r.actor_kind='guest' and r.actor_id=v_guest.id and r.command_id=p_command_id;if v_existing.id is not null then if v_existing.request_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='55000';end if;return v_existing.result;end if;if v_state.global_game_state<>'MISSION_06' then raise exception 'M06 is not current stage' using errcode='55000';end if;
 begin select i.* into v_instance from public.bunker_mission_instances i where i.event_id=v_event_id and i.run_nonce=v_state.run_nonce and i.id=(p_payload->>'instanceId')::uuid for update;exception when invalid_text_representation then raise exception 'invalid M06 instance id' using errcode='22023';end;if v_instance.id is null or v_instance.mission_code<>'MISSION_06' or v_instance.status<>'active' then raise exception 'M06 instance unavailable' using errcode='55000';end if;select m.* into v_member from public.bunker_mission_members m where m.instance_id=v_instance.id and m.guest_id=v_guest.id;select p.* into v_profile from public.bunker_guest_profiles p where p.run_nonce=v_state.run_nonce and p.guest_id=v_guest.id for update;
 select public._bunker_v2_m06_fragment((f.value->>'fragmentIndex')::integer,(f.value->>'totalFragments')::integer) into v_fragment from jsonb_array_elements(v_instance.definition->'fragments') f(value) where f.value->>'wagonId'=v_guest.carriage_id::text;v_expected_key:=v_fragment->>'key';if v_expected_key is null then raise exception 'M06 wagon fragment missing' using errcode='55000';end if;
 if p_command_type='reveal_fragment' then
  if p_payload->>'fragmentKey'<>v_expected_key then raise exception 'M06 fragment does not belong to guest wagon' using errcode='42501';end if;
  insert into public.bunker_mission_decisions(event_id,run_nonce,instance_id,decision_key,actor_kind,actor_id,actor_scope_key,status,instance_version,command_id,payload,outcome,confirmed_at) values(v_event_id,v_state.run_nonce,v_instance.id,'m06_fragment','wagon',v_guest.id,v_guest.carriage_id::text,'confirmed',v_instance.instance_version,p_command_id,jsonb_build_object('fragmentKey',v_expected_key),jsonb_build_object('shared',true),v_now) on conflict(instance_id,decision_key,actor_kind,actor_scope_key) do update set actor_id=excluded.actor_id,command_id=excluded.command_id,payload=excluded.payload,outcome=excluded.outcome,confirmed_at=excluded.confirmed_at;
 elsif p_command_type='cast_vote' then
  if v_member.id is null then raise exception 'M06 vote requires frozen member' using errcode='42501';end if;v_vote:=upper(btrim(p_payload->>'vote'));if v_vote not in ('A','B','C') then raise exception 'M06 vote must be A B or C' using errcode='22023';end if;
  insert into public.bunker_mission_decisions(event_id,run_nonce,instance_id,decision_key,actor_kind,actor_id,actor_scope_key,status,instance_version,command_id,payload,outcome,confirmed_at) values(v_event_id,v_state.run_nonce,v_instance.id,'m06_vote','guest',v_guest.id,v_guest.id::text,'confirmed',v_instance.instance_version,p_command_id,jsonb_build_object('vote',v_vote),jsonb_build_object('vote',v_vote),v_now) on conflict(instance_id,decision_key,actor_kind,actor_scope_key) do update set command_id=excluded.command_id,payload=excluded.payload,outcome=excluded.outcome,confirmed_at=excluded.confirmed_at;
  v_consensus:=public._bunker_v2_m06_consensus(v_instance.id);select jsonb_array_length(v_consensus),count(*) filter(where value->>'consensus' is not null)::integer,count(distinct value->>'consensus')::integer,max(value->>'consensus') into v_total,v_ready,v_distinct,v_global from jsonb_array_elements(v_consensus);
  if v_ready=v_total and v_distinct=1 and v_global=public._bunker_v2_m06_correct_protocol() then
   select a.id into v_entry_sector from public.bunker_archive_entries a where a.run_nonce=v_state.run_nonce and a.artifact_key='SECTOR-04' limit 1;if v_entry_sector is null then insert into public.bunker_archive_entries(event_id,run_nonce,carriage_id,artifact_key,content_type,content,decryption_status,decoded_at) values(v_event_id,v_state.run_nonce,null,'SECTOR-04','document',jsonb_build_object('title','SECTOR 04','route','TUNNEL B','summary','Безопасная точка Бункера подтверждена общим протоколом.'),'decoded',v_now) returning id into v_entry_sector;end if;
   select a.id into v_entry_code from public.bunker_archive_entries a where a.run_nonce=v_state.run_nonce and a.artifact_key='ACCESS-4719' limit 1;if v_entry_code is null then insert into public.bunker_archive_entries(event_id,run_nonce,carriage_id,artifact_key,content_type,content,decryption_status,decoded_at) values(v_event_id,v_state.run_nonce,null,'ACCESS-4719','code',jsonb_build_object('title','Код доступа','code','4719'),'decoded',v_now) returning id into v_entry_code;end if;
   insert into public.bunker_archive_entitlements(event_id,run_nonce,archive_entry_id,carriage_id,owner_scope_kind,owner_scope_key,status) values(v_event_id,v_state.run_nonce,v_entry_sector,null,'global','global','active') on conflict(run_nonce,archive_entry_id,owner_scope_kind,owner_scope_key) do nothing;insert into public.bunker_archive_entitlements(event_id,run_nonce,archive_entry_id,carriage_id,owner_scope_kind,owner_scope_key,status) values(v_event_id,v_state.run_nonce,v_entry_code,null,'global','global','active') on conflict(run_nonce,archive_entry_id,owner_scope_kind,owner_scope_key) do nothing;
   update public.bunker_final_parameters set status='resolved',source_kind='mission06',source_instance_id=v_instance.id,public_hint=jsonb_build_object('source','Общий протокол'),resolved_at=v_now where event_id=v_event_id and run_nonce=v_state.run_nonce and parameter_key in ('sector','access_code');
   update public.bunker_wagon_state set sector04_found=true,updated_at=now() where event_id=v_event_id and run_nonce=v_state.run_nonce;
   update public.bunker_mission_instances set status='completed',completed_at=v_now,outcome=jsonb_build_object('status','success','protocol','B','sector','04','accessCode','4719') where id=v_instance.id;update public.bunker_mission_members set member_status='completed',updated_at=v_now where instance_id=v_instance.id;
  end if;
 elsif p_command_type='use_ability' then
  if p_payload->>'problemKey'<>'protocol' or v_profile.special_ability not in ('bunker_knowledge','plan_analysis','archive_search','organize_data','terminal_hack','weak_signal','system_access','coordinate_analysis') or v_profile.ability_uses_remaining<1 then raise exception 'M06 protocol ability unavailable' using errcode='42501';end if;v_hint:=case v_profile.special_ability when 'bunker_knowledge' then 'Старые обозначения объекта используют TUNNEL B и номер сектора из двух цифр.' when 'plan_analysis' then 'На плане линия TUNNEL B стыкуется с сеткой сектора 04.' when 'archive_search' then 'BK-17 подтверждает: фрагменты нужно сопоставлять в порядке вагонов.' when 'organize_data' then 'Разделите данные на три группы: маршрут, сектор, код. Они должны образовать одну непротиворечивую цепочку.' when 'terminal_hack' then 'Контрольная сумма протокола B совпадает с архивной.' when 'system_access' then 'Служебная система помечает вариант B как совместимый с архивом BK-17.' when 'weak_signal' then 'В слабом сигнале различимы: «…B…» и «…04…».' else 'Номер сектора должен совпасть с двухзначной сеткой защищённого объекта.' end;insert into public.bunker_ability_uses(event_id,run_nonce,instance_id,guest_id,ability_key,problem_key,status,command_id,effect,committed_at) values(v_event_id,v_state.run_nonce,v_instance.id,v_guest.id,v_profile.special_ability,'protocol','committed',p_command_id,jsonb_build_object('hint',v_hint),v_now);update public.bunker_guest_profiles set ability_uses_remaining=ability_uses_remaining-1,ability_used_at=v_now where run_nonce=v_state.run_nonce and guest_id=v_guest.id and ability_uses_remaining>0;
 else raise exception 'unsupported M06 command type' using errcode='22023';end if;
 v_result:=jsonb_build_object('contractVersion',2,'status','accepted','commandId',p_command_id,'commandType',p_command_type);insert into public.bunker_command_receipts(event_id,run_nonce,actor_kind,actor_id,command_id,command_type,request_hash,result) values(v_event_id,v_state.run_nonce,'guest',v_guest.id,p_command_id,p_command_type,v_hash,v_result);insert into public.bunker_game_events(event_id,run_nonce,carriage_id,guest_id,event_type,actor_type,actor_id,command_id,correlation_id,instance_id,schema_version,payload) values(v_event_id,v_state.run_nonce,v_guest.carriage_id,v_guest.id,'m06_'||p_command_type,'guest',v_guest.id,p_command_id,p_command_id,v_instance.id,2,jsonb_build_object('missionCode','MISSION_06','commandType',p_command_type));return v_result;
end;$$;
revoke all on function public._submit_bunker_command_m06(text,text,uuid,text,jsonb) from public,anon,authenticated;

create or replace function public.submit_bunker_command(p_event_slug text,p_device_key text,p_command_id uuid,p_command_type text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event_id uuid;v_guest_id uuid;v_state public.bunker_state%rowtype;v_existing public.bunker_command_receipts%rowtype;v_hash text;v_instance_id uuid;begin select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then raise exception 'Bunker event not found' using errcode='P0002';end if;v_guest_id:=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest_id is null then raise exception 'registered Bunker guest required' using errcode='42501';end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id for update;if v_state.run_nonce is null then raise exception 'active Bunker V2 run required' using errcode='55000';end if;v_hash:=encode(extensions.digest(convert_to(jsonb_build_object('commandType',p_command_type,'payload',p_payload)::text,'UTF8'),'sha256'),'hex');select r.* into v_existing from public.bunker_command_receipts r where r.run_nonce=v_state.run_nonce and r.actor_kind='guest' and r.actor_id=v_guest_id and r.command_id=p_command_id;if v_existing.id is not null then if v_existing.request_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='55000';end if;return v_existing.result;end if;if v_state.global_game_state='MISSION_01' then begin v_instance_id:=(p_payload->>'instanceId')::uuid;exception when others then v_instance_id:=null;end;perform 1 from public.bunker_mission_instances i where i.id=v_instance_id for update;perform 1 from public.bunker_mission_members m where m.instance_id=v_instance_id order by m.id for update;return public._submit_bunker_command_m01(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_02' then return public._submit_bunker_command_m02(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_03' then return public._submit_bunker_command_m03(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_04' then return public._submit_bunker_command_m04(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_05' then return public._submit_bunker_command_m05(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_06' then return public._submit_bunker_command_m06(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);end if;raise exception 'Bunker command unavailable at current stage' using errcode='55000';end;$$;
revoke all on function public.submit_bunker_command(text,text,uuid,text,jsonb) from public,anon,authenticated;grant execute on function public.submit_bunker_command(text,text,uuid,text,jsonb) to anon,authenticated;

create or replace function public.get_guest_bunker_v2_m06(p_event_slug text,p_device_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest public.guests%rowtype;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_carriage public.carriages%rowtype;v_profile public.bunker_guest_profiles%rowtype;v_member public.bunker_mission_members%rowtype;v_fragment_row jsonb;v_private jsonb;v_shared boolean;v_revealed jsonb;v_revealed_count integer;v_total integer;v_selected text;v_ability jsonb:=null;v_hint text;v_now timestamptz:=clock_timestamp();begin
 select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select g.* into v_guest from public.guests g where g.event_id=v_event_id and g.id=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest.id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='MISSION_06' limit 1;if v_instance.id is null or v_state.global_game_state not in ('MISSION_06','UNKNOWN_PASSENGER','BREAK_BEFORE_FINAL','FINAL_30','BUNKER_OPEN','FINISHED') then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select c.* into v_carriage from public.carriages c where c.id=v_guest.carriage_id;select p.* into v_profile from public.bunker_guest_profiles p where p.run_nonce=v_state.run_nonce and p.guest_id=v_guest.id;select m.* into v_member from public.bunker_mission_members m where m.instance_id=v_instance.id and m.guest_id=v_guest.id;
 select f.value into v_fragment_row from jsonb_array_elements(v_instance.definition->'fragments') f(value) where f.value->>'wagonId'=v_guest.carriage_id::text;v_private:=public._bunker_v2_m06_fragment((v_fragment_row->>'fragmentIndex')::integer,(v_fragment_row->>'totalFragments')::integer);v_total:=jsonb_array_length(v_instance.definition->'fragments');select exists(select 1 from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m06_fragment' and d.actor_kind='wagon' and d.actor_scope_key=v_guest.carriage_id::text and d.status='confirmed') into v_shared;
 select coalesce(jsonb_agg(public._bunker_v2_m06_fragment((f.value->>'fragmentIndex')::integer,(f.value->>'totalFragments')::integer) order by (f.value->>'fragmentIndex')::integer),'[]'::jsonb),count(*)::integer into v_revealed,v_revealed_count from jsonb_array_elements(v_instance.definition->'fragments') f(value) where exists(select 1 from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m06_fragment' and d.actor_kind='wagon' and d.actor_scope_key=f.value->>'wagonId' and d.status='confirmed');select d.payload->>'vote' into v_selected from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m06_vote' and d.actor_id=v_guest.id limit 1;select u.effect->>'hint' into v_hint from public.bunker_ability_uses u where u.instance_id=v_instance.id and u.guest_id=v_guest.id and u.problem_key='protocol' limit 1;if v_profile.special_ability in ('bunker_knowledge','plan_analysis','archive_search','organize_data','terminal_hack','weak_signal','system_access','coordinate_analysis') then v_ability:=jsonb_build_object('available',v_profile.ability_uses_remaining>0 and v_hint is null,'key',v_profile.special_ability,'label',v_profile.ability_description,'hint',coalesce(v_hint,'Можно один раз запросить дополнительную проверку общего протокола.'));end if;
 return jsonb_strip_nulls(jsonb_build_object('contractVersion',2,'status',case when v_instance.status='completed' then 'completed' else 'active' end,'serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now),'instanceId',v_instance.id,'instanceVersion',v_instance.instance_version,'title',v_instance.definition->>'title','intro',v_instance.definition->>'intro','viewer',jsonb_build_object('wagonId',v_guest.carriage_id,'wagonNumber',v_carriage.number,'canVote',v_member.id is not null),'privateFragment',v_private,'fragmentShared',v_shared,'revealedFragments',v_revealed,'fragmentsRevealed',v_revealed_count,'fragmentsTotal',v_total,'options',v_instance.definition->'options','selectedVote',v_selected,'wagonConsensus',public._bunker_v2_m06_consensus(v_instance.id),'ability',v_ability,'outcome',case when v_instance.status='completed' then v_instance.outcome else null end));end;$$;
revoke all on function public.get_guest_bunker_v2_m06(text,text) from public,anon,authenticated;grant execute on function public.get_guest_bunker_v2_m06(text,text) to anon,authenticated;

create or replace function public._bunker_v2_m06_screen_payload(p_event_id uuid,p_run_nonce uuid,p_instance_id uuid) returns jsonb language sql stable security definer set search_path='' as $$ with consensus as (select value from jsonb_array_elements(public._bunker_v2_m06_consensus(p_instance_id))), wagons as (select value->>'wagonId' wagon_id,value->>'label' label,(value->>'consensus') is not null ready from consensus), fragments as (select count(*)::integer n from public.bunker_mission_decisions d where d.instance_id=p_instance_id and d.decision_key='m06_fragment' and d.actor_kind='wagon' and d.status='confirmed') select jsonb_build_object('fragmentsRevealed',(select n from fragments),'fragmentsTotal',(select jsonb_array_length(i.definition->'fragments') from public.bunker_mission_instances i where i.id=p_instance_id),'wagons',coalesce((select jsonb_agg(jsonb_build_object('wagonId',wagon_id,'label',label,'consensusReady',ready) order by label) from wagons),'[]'::jsonb)); $$;
revoke all on function public._bunker_v2_m06_screen_payload(uuid,uuid,uuid) from public,anon,authenticated;
create or replace function public.get_bunker_v2_m06_screen(p_event_slug text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event_id uuid;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_payload jsonb;v_now timestamptz:=clock_timestamp();begin select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='MISSION_06' limit 1;v_payload:=public._bunker_v2_m06_screen_payload(v_event_id,v_state.run_nonce,v_instance.id);return jsonb_build_object('contractVersion',2,'status',case when v_state.global_game_state='MISSION_06' then 'active' else 'completed' end,'serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now),'title','Общий протокол')||v_payload;end;$$;
revoke all on function public.get_bunker_v2_m06_screen(text) from public,anon,authenticated;grant execute on function public.get_bunker_v2_m06_screen(text) to anon,authenticated;
create or replace function public.get_owner_bunker_v2_m06(p_event_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_state public.bunker_state%rowtype;v_instance public.bunker_mission_instances%rowtype;v_payload jsonb;v_now timestamptz:=clock_timestamp();begin perform public._require_bunker_owner(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='MISSION_06' limit 1;v_payload:=public._bunker_v2_m06_screen_payload(p_event_id,v_state.run_nonce,v_instance.id);return jsonb_build_object('contractVersion',2,'status',case when v_state.global_game_state='MISSION_06' then 'active' else 'completed' end,'serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now),'title','Общий протокол')||v_payload;end;$$;
revoke all on function public.get_owner_bunker_v2_m06(uuid) from public,anon,authenticated;grant execute on function public.get_owner_bunker_v2_m06(uuid) to authenticated;
