alter table public.bunker_state
  add column phase text not null default 'emergency'
    check (phase in ('emergency', 'dossier_1', 'dossier_2', 'mission_a', 'mission_b', 'final', 'completed')),
  add column phase_started_at timestamptz,
  add column unlocked_at timestamptz,
  add column run_nonce uuid;

create table public.bunker_guest_profiles (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  run_nonce uuid not null,
  guest_id uuid not null references public.guests(id) on delete cascade,
  profession text not null,
  profile text not null,
  health text not null,
  hobby text not null,
  baggage text not null,
  hidden_fact text not null,
  created_at timestamptz not null default now(),
  unique (run_nonce, guest_id)
);

create table public.bunker_mission_templates (
  id uuid primary key default gen_random_uuid(),
  stage text not null check (stage in ('mission_a', 'mission_b')),
  carriage_number integer not null check (carriage_number between 1 and 5),
  title text not null,
  prompt text not null,
  options jsonb not null default '[]'::jsonb check (jsonb_typeof(options) = 'array'),
  correct_answer text not null,
  success_copy text not null,
  hint_copy text not null,
  unique (stage, carriage_number)
);

create table public.bunker_team_progress (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  run_nonce uuid not null,
  carriage_id uuid not null references public.carriages(id) on delete cascade,
  stage text not null check (stage in ('mission_a', 'mission_b')),
  mission_template_id uuid not null references public.bunker_mission_templates(id) on delete restrict,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  completed_at timestamptz,
  completed_by_guest_id uuid references public.guests(id) on delete set null,
  reward_fragment text check (reward_fragment is null or reward_fragment ~ '^[0-9]{2}$'),
  updated_at timestamptz not null default now(),
  unique (run_nonce, carriage_id, stage)
);

create table public.bunker_final_attempts (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  run_nonce uuid not null,
  guest_id uuid references public.guests(id) on delete set null,
  submitted_code_hash text not null,
  correct boolean not null,
  created_at timestamptz not null default now()
);

create index bunker_guest_profiles_event_run_idx
  on public.bunker_guest_profiles(event_id, run_nonce);
create index bunker_team_progress_event_run_idx
  on public.bunker_team_progress(event_id, run_nonce, stage);
create index bunker_final_attempts_event_run_idx
  on public.bunker_final_attempts(event_id, run_nonce, created_at desc);

alter table public.bunker_guest_profiles enable row level security;
alter table public.bunker_mission_templates enable row level security;
alter table public.bunker_team_progress enable row level security;
alter table public.bunker_final_attempts enable row level security;

revoke all on table public.bunker_guest_profiles from public, anon, authenticated;
revoke all on table public.bunker_mission_templates from public, anon, authenticated;
revoke all on table public.bunker_team_progress from public, anon, authenticated;
revoke all on table public.bunker_final_attempts from public, anon, authenticated;

insert into public.bunker_mission_templates(
  stage, carriage_number, title, prompt, options, correct_answer, success_copy, hint_copy
)
values
  (
    'mission_a', 1, 'АРХИВ · ВАГОН 01',
    'Система охлаждения выдержит только один из трёх режимов. Какой режим безопаснее оставить на 30 минут?',
    '["МАКСИМУМ", "СТАБИЛЬНЫЙ", "АВАРИЙНЫЙ"]'::jsonb,
    'СТАБИЛЬНЫЙ', 'Контур принят. Вагон 01 синхронизирован.',
    'Ищите вариант, который рассчитан не на пик, а на устойчивую работу.'
  ),
  (
    'mission_a', 2, 'НАБЛЮДЕНИЕ · ВАГОН 02',
    'На панели три сигнала: один мигает часто, второй горит постоянно, третий погас. Какой сигнал лучше выбрать как опорный?',
    '["МИГАЮЩИЙ", "ПОСТОЯННЫЙ", "ПОГАСШИЙ"]'::jsonb,
    'ПОСТОЯННЫЙ', 'Опорный сигнал подтверждён. Вагон 02 в контуре.',
    'Опорный сигнал должен оставаться предсказуемым.'
  ),
  (
    'mission_a', 3, 'ДАВЛЕНИЕ · ВАГОН 03',
    'Шлюз показывает 3, 7 и 11 условных единиц. Центральный диапазон системы — от 5 до 9. Какое значение оставить?',
    '["3", "7", "11"]'::jsonb,
    '7', 'Давление стабилизировано. Вагон 03 допущен.',
    'Нужное значение находится внутри указанного диапазона.'
  ),
  (
    'mission_a', 4, 'ЭНЕРГИЯ · ВАГОН 04',
    'Есть три линии питания: 20%, 50% и 90%. Резерв должен быть не пустым и не перегруженным. Какую линию выбрать?',
    '["20%", "50%", "90%"]'::jsonb,
    '50%', 'Резервная линия выбрана. Вагон 04 подключён.',
    'Выбирайте середину между недостатком и перегрузкой.'
  ),
  (
    'mission_a', 5, 'СВЯЗЬ · ВАГОН 05',
    'Канал связи можно оставить в режимах «ЭХО», «ПРЯМОЙ» или «ТИШИНА». Какой режим передаст сообщение без повторов?',
    '["ЭХО", "ПРЯМОЙ", "ТИШИНА"]'::jsonb,
    'ПРЯМОЙ', 'Канал очищен. Вагон 05 на связи.',
    'Нужен режим без повторения и без отключения сигнала.'
  ),
  (
    'mission_b', 1, 'ШИФР · ВАГОН 01',
    'Кодовая последовательность: 2 · 4 · 8 · 16 · ?. Введите следующее число.',
    '[]'::jsonb,
    '32', 'Фрагмент доступа выдан вагону 01.',
    'Каждое следующее число в два раза больше предыдущего.'
  ),
  (
    'mission_b', 2, 'ШИФР · ВАГОН 02',
    'Кодовая последовательность: 3 · 6 · 9 · 12 · ?. Введите следующее число.',
    '[]'::jsonb,
    '15', 'Фрагмент доступа выдан вагону 02.',
    'Шаг последовательности одинаковый.'
  ),
  (
    'mission_b', 3, 'ШИФР · ВАГОН 03',
    'На табло: 1 · 1 · 2 · 3 · 5 · ?. Введите следующее число.',
    '[]'::jsonb,
    '8', 'Фрагмент доступа выдан вагону 03.',
    'Каждое число складывается из двух предыдущих.'
  ),
  (
    'mission_b', 4, 'ШИФР · ВАГОН 04',
    'Система считает назад: 25 · 20 · 15 · 10 · ?. Введите следующее число.',
    '[]'::jsonb,
    '5', 'Фрагмент доступа выдан вагону 04.',
    'Каждый шаг уменьшает значение на пять.'
  ),
  (
    'mission_b', 5, 'ШИФР · ВАГОН 05',
    'Последовательность квадратов: 1 · 4 · 9 · 16 · ?. Введите следующее число.',
    '[]'::jsonb,
    '25', 'Фрагмент доступа выдан вагону 05.',
    'Это квадраты последовательных целых чисел.'
  );

create or replace function public._bunker_guest_id(
  p_event_slug text,
  p_device_key text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
  v_guest_id uuid;
begin
  if length(coalesce(p_device_key, '')) < 8 then
    return null;
  end if;

  select e.id into v_event_id
  from public.events e
  where e.slug = public._normalize_spaces(p_event_slug);

  if v_event_id is null then
    return null;
  end if;

  select b.guest_id into v_guest_id
  from public.guest_device_bindings b
  where b.event_id = v_event_id
    and b.device_key_hash = public._device_hash(p_device_key);

  return v_guest_id;
end;
$$;

create or replace function public._ensure_bunker_guest_profile(
  p_event_id uuid,
  p_run_nonce uuid,
  p_guest_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_professions text[] := array[
    'АРХИТЕКТОР', 'ФЕЛЬДШЕР', 'ИНЖЕНЕР СВЯЗИ', 'ПОВАР', 'БИОЛОГ', 'МЕХАНИК',
    'ЭЛЕКТРИК', 'ПСИХОЛОГ', 'ГЕОЛОГ', 'ФОТОГРАФ', 'АГРОНОМ', 'ПРОГРАММИСТ',
    'СПАСАТЕЛЬ', 'УЧИТЕЛЬ', 'ВЕТЕРИНАР', 'КАРТОГРАФ', 'СТОЛЯР', 'ХИМИК',
    'РАДИОТЕХНИК', 'СТРОИТЕЛЬ', 'ФАРМАЦЕВТ', 'ПИЛОТ ДРОНА', 'ЛОГИСТ', 'МЕТЕОРОЛОГ',
    'САНТЕХНИК', 'ПЕРЕВОДЧИК', 'САДОВНИК', 'ДИЗАЙНЕР', 'МУЗЫКАНТ', 'МАТЕМАТИК'
  ];
  v_profiles text[] := array[
    '24 ГОДА · БЫСТРО УЧИТСЯ', '27 ЛЕТ · СПОКОЕН ПОД ДАВЛЕНИЕМ', '29 ЛЕТ · РАНО ВСТАЁТ',
    '31 ГОД · ЛЮБИТ ПОРЯДОК', '33 ГОДА · НОЧНАЯ СОВА', '35 ЛЕТ · ХОРОШАЯ ПАМЯТЬ',
    '37 ЛЕТ · УМЕЕТ ДОГОВАРИВАТЬСЯ', '39 ЛЕТ · НЕ БОИТСЯ ВЫСОТЫ', '41 ГОД · ТЕРПЕЛИВ',
    '43 ГОДА · ПРИВЫК РАБОТАТЬ В КОМАНДЕ', '45 ЛЕТ · ЗНАЕТ ПЕРВУЮ ПОМОЩЬ', '47 ЛЕТ · ЛЮБИТ ИНСТРУКЦИИ',
    '26 ЛЕТ · БЫСТРО СЧИТАЕТ', '28 ЛЕТ · ХОРОШО ОРИЕНТИРУЕТСЯ', '30 ЛЕТ · НЕ ПАНИКУЕТ',
    '32 ГОДА · ВНИМАТЕЛЕН К ДЕТАЛЯМ', '34 ГОДА · УМЕЕТ ИМПРОВИЗИРОВАТЬ', '36 ЛЕТ · СИЛЬНЫЙ ПЕРЕГОВОРЩИК',
    '38 ЛЕТ · ЛЮБИТ ГОЛОВОЛОМКИ', '40 ЛЕТ · ПРИВЫК К ДЕЖУРСТВАМ', '42 ГОДА · СИСТЕМНО МЫСЛИТ',
    '44 ГОДА · ХОРОШО ГОТОВИТ', '46 ЛЕТ · МНОГО ПУТЕШЕСТВОВАЛ', '48 ЛЕТ · УМЕЕТ ЧИНИТЬ ВЕЩИ',
    '25 ЛЕТ · БЫСТРАЯ РЕАКЦИЯ', '27 ЛЕТ · ХОРОШИЙ СЛУХ', '29 ЛЕТ · ЛЕГКО ЗАСЫПАЕТ',
    '31 ГОД · ХОРОШО РИСУЕТ', '33 ГОДА · ЛЮБИТ ПЛАНИРОВАТЬ', '35 ЛЕТ · НЕ ТЕРЯЕТ ЮМОР'
  ];
  v_health text[] := array[
    'НУЖНЫ ОЧКИ ДЛЯ МЕЛКОГО ТЕКСТА', 'НЕ ЛЮБИТ ХОЛОД', 'БЫСТРО УСТАЁТ БЕЗ КОФЕ',
    'УКАЧИВАЕТ В ТРАНСПОРТЕ', 'ЧУВСТВИТЕЛЕН К ГРОМКИМ ЗВУКАМ', 'НУЖЕН РЕГУЛЯРНЫЙ СОН',
    'НЕ ЛЮБИТ ЖАРУ', 'СТАРАЯ СПОРТИВНАЯ ТРАВМА КОЛЕНА', 'ЛЁГКАЯ АЛЛЕРГИЯ НА ПЫЛЬ',
    'ПЛОХО ВИДИТ В ТЕМНОТЕ', 'НЕ ПЕРЕНОСИТ ОСТРУЮ ЕДУ', 'ИНогда БОЛИТ СПИНА',
    'БЫСТРО МЁРЗНУТ РУКИ', 'НЕ ЛЮБИТ ЗАМКНУТЫЕ ЛИФТЫ', 'НУЖНО МНОГО ВОДЫ',
    'СИЛЬНО РЕАГИРУЕТ НА НЕДОСЫП', 'ПЕРИОДИЧЕСКИ ШУМИТ В УШАХ', 'СЛАБЫЙ ВЕСТИБУЛЯРНЫЙ АППАРАТ',
    'НЕ МОЖЕТ ДОЛГО СИДЕТЬ БЕЗ ДВИЖЕНИЯ', 'ЧУВСТВИТЕЛЕН К ЯРКОМУ СВЕТУ', 'НЕ ЛЮБИТ ВЫСОТУ',
    'НЕ ЛЮБИТ ТЕМНОТУ', 'ПРЕДПОЧИТАЕТ ТИХИЕ ПОМЕЩЕНИЯ', 'НУЖЕН СТРОГИЙ РЕЖИМ ПИТАНИЯ',
    'БЫСТРО ВОССТАНАВЛИВАЕТСЯ ПОСЛЕ НАГРУЗКИ', 'ХОРОШАЯ ВЫНОСЛИВОСТЬ', 'ХОРОШЕЕ ЗРЕНИЕ',
    'ХОРОШИЙ СЛУХ', 'КРЕПКИЙ СОН', 'БЕЗ ОСОБЫХ ОГРАНИЧЕНИЙ'
  ];
  v_hobbies text[] := array[
    'ШАХМАТЫ', 'ПОХОДЫ', 'РЫБАЛКА', 'КУЛИНАРИЯ', 'НАСТОЛЬНЫЕ ИГРЫ', 'БЕГ',
    'РЕМОНТ ТЕХНИКИ', 'ФОТОГРАФИЯ', 'САДОВОДСТВО', 'ПЛАВАНИЕ', 'КАРАОКЕ', 'ЙОГА',
    'ОРИЕНТИРОВАНИЕ', '3D-МОДЕЛИРОВАНИЕ', 'ВЕЛОСИПЕД', 'ПАЙКА', 'ЧТЕНИЕ КАРТ', 'ИНОСТРАННЫЕ ЯЗЫКИ',
    'ДЕРЕВООБРАБОТКА', 'МУЗЫКА', 'ТАНЦЫ', 'АСТРОНОМИЯ', 'ПЕРВАЯ ПОМОЩЬ', 'КВИЗЫ',
    'КЕМПИНГ', 'РЕМОНТ МЕБЕЛИ', 'РИСОВАНИЕ', 'СБОР ГРИБОВ', 'ПЕЧАТЬ НА 3D-ПРИНТЕРЕ', 'ГОЛОВОЛОМКИ'
  ];
  v_baggage text[] := array[
    'АПТЕЧКА', 'ФОНАРЬ И БАТАРЕЙКИ', 'НАБОР ИНСТРУМЕНТОВ', '20 МЕТРОВ ВЕРЁВКИ', 'ФИЛЬТР ДЛЯ ВОДЫ',
    'РАЦИЯ', 'КОМПАС', 'ПАУЭРБАНК', 'СПАЛЬНЫЙ МЕШОК', 'КОРОБКА КОНСЕРВОВ',
    'СЕМЕНА ОВОЩЕЙ', 'ТЕРМОС', 'МУЛЬТИТУЛ', 'БУМАЖНАЯ КАРТА', 'НАБОР ДЛЯ ШИТЬЯ',
    'ПОРТАТИВНАЯ КОЛОНКА', 'ДВЕ КНИГИ ПО РЕМОНТУ', 'БИНОКЛЬ', 'КАТУШКА ПРОВОДА', 'ПОХОДНАЯ ГОРЕЛКА',
    'ЗАПАС НОСКОВ', 'НАБОР СПЕЦИЙ', 'СКОТЧ И СТЯЖКИ', 'МАЛЕНЬКАЯ СОЛНЕЧНАЯ ПАНЕЛЬ', 'ТЕРМОПЛЕД',
    'БЛОКНОТ И КАРАНДАШИ', 'НАБОР КЛЮЧЕЙ', 'ЗАЩИТНЫЕ ПЕРЧАТКИ', 'ПОХОДНАЯ ПОСУДА', 'КОЛОДА КАРТ'
  ];
  v_facts text[] := array[
    'УМЕЕТ ОТКРЫВАТЬ КОНСЕРВЫ ЛОЖКОЙ', 'ПОМНИТ ТЕЛЕФОННЫЕ НОМЕРА С ПЕРВОГО РАЗА', 'МОЖЕТ СПАТЬ ПРИ ЛЮБОМ ШУМЕ',
    'ЗНАЕТ АЗБУКУ МОРЗЕ', 'УМЕЕТ ЗАВЯЗЫВАТЬ 12 УЗЛОВ', 'ОДНАЖДЫ ЖИЛ БЕЗ ИНТЕРНЕТА МЕСЯЦ',
    'РАЗЛИЧАЕТ СЕВЕР ПО ЗВЁЗДАМ', 'МОЖЕТ ПОЧИНИТЬ КРАН', 'УМЕЕТ ПЕЧЬ ХЛЕБ',
    'ЗНАЕТ, КАК СОБРАТЬ ПРОСТОЙ РАДИОПРИЁМНИК', 'МОЖЕТ РАЗВЕСТИ ОГОНЬ С ОДНОЙ СПИЧКИ', 'НЕ ПРОИГРЫВАЕТ В КРЕСТИКИ-НОЛИКИ',
    'УМЕЕТ БЫСТРО СЧИТАТЬ В УМЕ', 'МОЖЕТ ОПРЕДЕЛИТЬ ВРЕМЯ БЕЗ ЧАСОВ', 'ПОЁТ ГРОМЧЕ ВСЕХ В КАРАОКЕ',
    'ХРАНИТ СЕКРЕТНЫЙ РЕЦЕПТ БОРЩА', 'НИКОГДА НЕ ТЕРЯЕТ НОСКИ В СТИРКЕ', 'УМЕЕТ ЧИТАТЬ ЭЛЕКТРИЧЕСКИЕ СХЕМЫ',
    'МОЖЕТ СОБРАТЬ ПАЛАТКУ В ТЕМНОТЕ', 'ЗНАЕТ ПЯТЬ СПОСОБОВ ЗАВАРИТЬ КОФЕ', 'ХОРОШО ИМИТИРУЕТ ЗВУКИ ЖИВОТНЫХ',
    'УМЕЕТ УСПОКАИВАТЬ ЛЮДЕЙ', 'БЫСТРО НАХОДИТ ОШИБКИ В ТЕКСТЕ', 'УМЕЕТ РАБОТАТЬ С ПАЯЛЬНИКОМ',
    'МОЖЕТ СДЕЛАТЬ ФИЛЬТР ИЗ ПОДРУЧНЫХ МАТЕРИАЛОВ', 'ЗНАЕТ ОСНОВЫ ЖЕСТОВОГО ЯЗЫКА', 'УМЕЕТ РАЗБИРАТЬСЯ В КАРТАХ',
    'МОЖЕТ ПРИГОТОВИТЬ УЖИН ИЗ ТРЁХ ПРОДУКТОВ', 'УМЕЕТ ЧИНИТЬ МОЛНИИ И ЗАСТЁЖКИ', 'НИКОГДА НЕ ЗАБЫВАЕТ, ГДЕ ОСТАВИЛ КЛЮЧИ'
  ];
begin
  if p_event_id is null or p_run_nonce is null or p_guest_id is null then
    return;
  end if;

  insert into public.bunker_guest_profiles(
    event_id, run_nonce, guest_id, profession, profile, health, hobby, baggage, hidden_fact
  )
  values (
    p_event_id,
    p_run_nonce,
    p_guest_id,
    v_professions[1 + floor(random() * array_length(v_professions, 1))::integer],
    v_profiles[1 + floor(random() * array_length(v_profiles, 1))::integer],
    v_health[1 + floor(random() * array_length(v_health, 1))::integer],
    v_hobbies[1 + floor(random() * array_length(v_hobbies, 1))::integer],
    v_baggage[1 + floor(random() * array_length(v_baggage, 1))::integer],
    v_facts[1 + floor(random() * array_length(v_facts, 1))::integer]
  )
  on conflict (run_nonce, guest_id) do nothing;
end;
$$;

create or replace function public._ensure_bunker_team_progress(
  p_event_id uuid,
  p_run_nonce uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.bunker_team_progress(
    event_id, run_nonce, carriage_id, stage, mission_template_id, reward_fragment
  )
  select
    p_event_id,
    p_run_nonce,
    c.id,
    t.stage,
    t.id,
    case
      when t.stage = 'mission_b' then lpad((10 + floor(random() * 90)::integer)::text, 2, '0')
      else null
    end
  from public.carriages c
  join public.bunker_mission_templates t on t.carriage_number = c.number
  where c.event_id = p_event_id and c.enabled
  on conflict (run_nonce, carriage_id, stage) do nothing;
end;
$$;

create or replace function public.owner_start_bunker(
  p_event_id uuid,
  p_duration_seconds integer default 1800
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_started_at timestamptz := clock_timestamp();
  v_run_nonce uuid := gen_random_uuid();
begin
  perform public._require_bunker_owner(p_event_id);

  if p_duration_seconds is null or p_duration_seconds not between 60 and 7200 then
    raise exception 'bunker duration must be between 60 and 7200 seconds' using errcode = '22023';
  end if;

  insert into public.bunker_state(
    event_id, status, started_at, duration_seconds, phase, phase_started_at,
    unlocked_at, run_nonce, updated_at
  )
  values (
    p_event_id, 'active', v_started_at, p_duration_seconds, 'emergency', v_started_at,
    null, v_run_nonce, now()
  )
  on conflict (event_id) do update
  set status = 'active',
      started_at = excluded.started_at,
      duration_seconds = excluded.duration_seconds,
      phase = 'emergency',
      phase_started_at = excluded.phase_started_at,
      unlocked_at = null,
      run_nonce = excluded.run_nonce,
      updated_at = now();

  update public.event_state
  set current_module = 'bunker',
      screen_mode = 'bunker_emergency',
      screen_pinned = true,
      updated_at = now()
  where event_id = p_event_id;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (
    p_event_id,
    auth.uid(),
    'bunker_started',
    jsonb_build_object(
      'startedAt', v_started_at,
      'durationSeconds', p_duration_seconds,
      'runNonce', v_run_nonce,
      'phase', 'emergency'
    )
  );

  return jsonb_build_object(
    'status', 'active',
    'startedAt', v_started_at,
    'durationSeconds', p_duration_seconds,
    'remainingSeconds', p_duration_seconds,
    'phase', 'emergency',
    'runNonce', v_run_nonce
  );
end;
$$;

create or replace function public.owner_stop_bunker(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public._require_bunker_owner(p_event_id);

  insert into public.bunker_state(
    event_id, status, started_at, duration_seconds, phase, phase_started_at, updated_at
  )
  values (p_event_id, 'idle', null, 1800, 'emergency', null, now())
  on conflict (event_id) do update
  set status = 'idle',
      started_at = null,
      phase = 'emergency',
      phase_started_at = null,
      updated_at = now();

  update public.event_state
  set current_module = 'idle',
      screen_mode = 'idle',
      screen_pinned = false,
      updated_at = now()
  where event_id = p_event_id;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (p_event_id, auth.uid(), 'bunker_stopped', '{}'::jsonb);

  return jsonb_build_object('status', 'idle');
end;
$$;

create or replace function public.owner_get_bunker_control(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
  v_now timestamptz := clock_timestamp();
  v_remaining integer := 0;
  v_active boolean := false;
begin
  perform public._require_bunker_owner(p_event_id);

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = p_event_id;

  if v_state.event_id is null then
    return jsonb_build_object(
      'status', 'idle',
      'durationSeconds', 1800,
      'soundEnabled', true,
      'phase', 'emergency',
      'serverNow', v_now
    );
  end if;

  v_active := v_state.status = 'active' and v_state.started_at is not null;
  if v_active then
    v_remaining := greatest(
      0,
      v_state.duration_seconds - floor(extract(epoch from (v_now - v_state.started_at)))::integer
    );
  end if;

  return jsonb_build_object(
    'status', case when v_active then 'active' else 'idle' end,
    'startedAt', case when v_active then v_state.started_at else null end,
    'durationSeconds', v_state.duration_seconds,
    'remainingSeconds', v_remaining,
    'soundEnabled', v_state.sound_enabled,
    'phase', v_state.phase,
    'phaseStartedAt', v_state.phase_started_at,
    'unlocked', v_state.unlocked_at is not null,
    'serverNow', v_now
  );
end;
$$;

create or replace function public.get_bunker_screen_state(p_event_slug text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
  v_state public.bunker_state%rowtype;
  v_now timestamptz := clock_timestamp();
  v_remaining integer := 0;
begin
  select e.id into v_event_id
  from public.events e
  where e.slug = public._normalize_spaces(p_event_slug);

  if v_event_id is null then
    return jsonb_build_object('status', 'not_found', 'serverNow', v_now);
  end if;

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = v_event_id;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.started_at is null then
    return jsonb_build_object('status', 'idle', 'serverNow', v_now);
  end if;

  v_remaining := greatest(
    0,
    v_state.duration_seconds - floor(extract(epoch from (v_now - v_state.started_at)))::integer
  );

  return jsonb_build_object(
    'status', 'active',
    'startedAt', v_state.started_at,
    'durationSeconds', v_state.duration_seconds,
    'remainingSeconds', v_remaining,
    'soundEnabled', v_state.sound_enabled,
    'phase', v_state.phase,
    'unlocked', v_state.unlocked_at is not null,
    'serverNow', v_now
  );
end;
$$;

create or replace function public.get_guest_bunker_state(
  p_event_slug text,
  p_device_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
  v_guest_id uuid;
  v_carriage_id uuid;
  v_carriage_number integer;
  v_state public.bunker_state%rowtype;
  v_profile public.bunker_guest_profiles%rowtype;
  v_progress public.bunker_team_progress%rowtype;
  v_template public.bunker_mission_templates%rowtype;
  v_now timestamptz := clock_timestamp();
  v_remaining integer := 0;
  v_rank integer := 0;
  v_stage text;
  v_dossier jsonb;
  v_team jsonb := null;
begin
  select e.id into v_event_id
  from public.events e
  where e.slug = public._normalize_spaces(p_event_slug);

  if v_event_id is null then
    return jsonb_build_object('status', 'not_found', 'serverNow', v_now);
  end if;

  v_guest_id := public._bunker_guest_id(p_event_slug, p_device_key);
  if v_guest_id is null then
    return jsonb_build_object('status', 'guest_not_found', 'serverNow', v_now);
  end if;

  select g.carriage_id, c.number
  into v_carriage_id, v_carriage_number
  from public.guests g
  join public.carriages c on c.id = g.carriage_id
  where g.id = v_guest_id and g.event_id = v_event_id;

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = v_event_id;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.started_at is null then
    return jsonb_build_object('status', 'idle', 'serverNow', v_now);
  end if;

  v_remaining := greatest(
    0,
    v_state.duration_seconds - floor(extract(epoch from (v_now - v_state.started_at)))::integer
  );

  v_rank := case v_state.phase
    when 'emergency' then 0
    when 'dossier_1' then 1
    when 'dossier_2' then 2
    when 'mission_a' then 3
    when 'mission_b' then 4
    when 'final' then 5
    when 'completed' then 6
    else 0
  end;

  if v_rank >= 1 and v_state.run_nonce is not null then
    perform public._ensure_bunker_guest_profile(v_event_id, v_state.run_nonce, v_guest_id);
    select p.* into v_profile
    from public.bunker_guest_profiles p
    where p.run_nonce = v_state.run_nonce and p.guest_id = v_guest_id;
  end if;

  v_dossier := case when v_rank >= 1 then jsonb_build_object(
    'profession', v_profile.profession,
    'profile', v_profile.profile,
    'health', case when v_rank >= 2 then v_profile.health else null end,
    'hobby', case when v_rank >= 2 then v_profile.hobby else null end,
    'baggage', case when v_rank >= 2 then v_profile.baggage else null end,
    'hiddenFact', case when v_rank >= 2 then v_profile.hidden_fact else null end
  ) else null end;

  if v_state.phase in ('mission_a', 'mission_b') and v_state.run_nonce is not null then
    v_stage := v_state.phase;
    select p.* into v_progress
    from public.bunker_team_progress p
    where p.run_nonce = v_state.run_nonce
      and p.carriage_id = v_carriage_id
      and p.stage = v_stage;

    if v_progress.id is not null then
      select t.* into v_template
      from public.bunker_mission_templates t
      where t.id = v_progress.mission_template_id;

      v_team := jsonb_build_object(
        'carriageNumber', v_carriage_number,
        'stage', v_stage,
        'mission', jsonb_build_object(
          'title', v_template.title,
          'prompt', v_template.prompt,
          'options', v_template.options
        ),
        'completed', v_progress.completed_at is not null,
        'attemptCount', v_progress.attempt_count,
        'fragment', case
          when v_progress.stage = 'mission_b' and v_progress.completed_at is not null
          then v_progress.reward_fragment
          else null
        end
      );
    end if;
  elsif v_state.run_nonce is not null and v_rank >= 5 then
    select p.* into v_progress
    from public.bunker_team_progress p
    where p.run_nonce = v_state.run_nonce
      and p.carriage_id = v_carriage_id
      and p.stage = 'mission_b';

    v_team := jsonb_build_object(
      'carriageNumber', v_carriage_number,
      'completed', v_progress.completed_at is not null,
      'fragment', case when v_progress.completed_at is not null then v_progress.reward_fragment else null end
    );
  end if;

  return jsonb_build_object(
    'status', 'active',
    'phase', v_state.phase,
    'phaseStartedAt', v_state.phase_started_at,
    'startedAt', v_state.started_at,
    'durationSeconds', v_state.duration_seconds,
    'remainingSeconds', v_remaining,
    'serverNow', v_now,
    'dossier', v_dossier,
    'team', v_team,
    'final', jsonb_build_object('unlocked', v_state.unlocked_at is not null)
  );
end;
$$;

create or replace function public.submit_guest_bunker_mission(
  p_event_slug text,
  p_device_key text,
  p_stage text,
  p_answer text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
  v_guest_id uuid;
  v_carriage_id uuid;
  v_state public.bunker_state%rowtype;
  v_progress public.bunker_team_progress%rowtype;
  v_template public.bunker_mission_templates%rowtype;
  v_answer text := upper(public._normalize_spaces(p_answer));
  v_correct boolean := false;
begin
  select e.id into v_event_id
  from public.events e
  where e.slug = public._normalize_spaces(p_event_slug);

  v_guest_id := public._bunker_guest_id(p_event_slug, p_device_key);
  if v_event_id is null or v_guest_id is null then
    raise exception 'guest access required' using errcode = '42501';
  end if;

  if p_stage not in ('mission_a', 'mission_b') then
    raise exception 'invalid bunker mission stage' using errcode = '22023';
  end if;

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = v_event_id;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.phase <> p_stage then
    raise exception 'bunker mission is not active' using errcode = '55000';
  end if;

  select g.carriage_id into v_carriage_id
  from public.guests g
  where g.id = v_guest_id and g.event_id = v_event_id;

  select p.* into v_progress
  from public.bunker_team_progress p
  where p.run_nonce = v_state.run_nonce
    and p.carriage_id = v_carriage_id
    and p.stage = p_stage
  for update;

  if v_progress.id is null then
    raise exception 'bunker team mission not initialized' using errcode = '55000';
  end if;

  if v_progress.completed_at is not null then
    return jsonb_build_object(
      'status', 'completed',
      'stage', p_stage,
      'fragment', case when p_stage = 'mission_b' then v_progress.reward_fragment else null end
    );
  end if;

  select t.* into v_template
  from public.bunker_mission_templates t
  where t.id = v_progress.mission_template_id;

  v_correct := v_answer = upper(public._normalize_spaces(v_template.correct_answer));

  update public.bunker_team_progress
  set attempt_count = attempt_count + 1,
      completed_at = case when v_correct then clock_timestamp() else completed_at end,
      completed_by_guest_id = case when v_correct then v_guest_id else completed_by_guest_id end,
      updated_at = now()
  where id = v_progress.id
  returning * into v_progress;

  if not v_correct then
    return jsonb_build_object(
      'status', 'incorrect',
      'stage', p_stage,
      'attemptCount', v_progress.attempt_count
    );
  end if;

  return jsonb_build_object(
    'status', 'completed',
    'stage', p_stage,
    'attemptCount', v_progress.attempt_count,
    'successCopy', v_template.success_copy,
    'fragment', case when p_stage = 'mission_b' then v_progress.reward_fragment else null end
  );
end;
$$;

create or replace function public.submit_guest_bunker_final_code(
  p_event_slug text,
  p_device_key text,
  p_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_event_id uuid;
  v_guest_id uuid;
  v_state public.bunker_state%rowtype;
  v_expected text;
  v_submitted text := regexp_replace(coalesce(p_code, ''), '[^0-9]', '', 'g');
  v_completed_count integer := 0;
  v_correct boolean := false;
begin
  select e.id into v_event_id
  from public.events e
  where e.slug = public._normalize_spaces(p_event_slug);

  v_guest_id := public._bunker_guest_id(p_event_slug, p_device_key);
  if v_event_id is null or v_guest_id is null then
    raise exception 'guest access required' using errcode = '42501';
  end if;

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = v_event_id
  for update;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.phase not in ('final', 'completed') then
    raise exception 'bunker final access is not active' using errcode = '55000';
  end if;

  if v_state.unlocked_at is not null then
    return jsonb_build_object('status', 'unlocked', 'unlocked', true);
  end if;

  select count(*)::integer,
         string_agg(p.reward_fragment, '' order by c.number)
  into v_completed_count, v_expected
  from public.bunker_team_progress p
  join public.carriages c on c.id = p.carriage_id
  where p.event_id = v_event_id
    and p.run_nonce = v_state.run_nonce
    and p.stage = 'mission_b'
    and p.completed_at is not null;

  if v_completed_count < 5 or v_expected is null then
    return jsonb_build_object('status', 'not_ready', 'unlocked', false);
  end if;

  v_correct := v_submitted = v_expected;

  insert into public.bunker_final_attempts(
    event_id, run_nonce, guest_id, submitted_code_hash, correct
  )
  values (
    v_event_id,
    v_state.run_nonce,
    v_guest_id,
    encode(extensions.digest(v_submitted, 'sha256'), 'hex'),
    v_correct
  );

  if not v_correct then
    return jsonb_build_object('status', 'incorrect', 'unlocked', false);
  end if;

  update public.bunker_state
  set unlocked_at = coalesce(unlocked_at, clock_timestamp()),
      updated_at = now()
  where event_id = v_event_id;

  return jsonb_build_object('status', 'unlocked', 'unlocked', true);
end;
$$;

create or replace function public.owner_get_bunker_quest(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
  v_now timestamptz := clock_timestamp();
  v_remaining integer := 0;
  v_teams jsonb := '[]'::jsonb;
begin
  perform public._require_bunker_owner(p_event_id);

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = p_event_id;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.started_at is null then
    return jsonb_build_object(
      'status', 'idle',
      'phase', 'emergency',
      'remainingSeconds', 0,
      'teams', '[]'::jsonb,
      'unlocked', false,
      'serverNow', v_now
    );
  end if;

  v_remaining := greatest(
    0,
    v_state.duration_seconds - floor(extract(epoch from (v_now - v_state.started_at)))::integer
  );

  if v_state.run_nonce is not null then
    select coalesce(jsonb_agg(team_row order by carriage_number), '[]'::jsonb)
    into v_teams
    from (
      select
        c.number as carriage_number,
        jsonb_build_object(
          'carriageId', c.id,
          'carriageNumber', c.number,
          'label', c.label,
          'missionA', jsonb_build_object(
            'completed', pa.completed_at is not null,
            'attemptCount', coalesce(pa.attempt_count, 0),
            'hint', ta.hint_copy
          ),
          'missionB', jsonb_build_object(
            'completed', pb.completed_at is not null,
            'attemptCount', coalesce(pb.attempt_count, 0),
            'fragment', case when pb.completed_at is not null then pb.reward_fragment else null end,
            'hint', tb.hint_copy
          )
        ) as team_row
      from public.carriages c
      left join public.bunker_team_progress pa
        on pa.run_nonce = v_state.run_nonce and pa.carriage_id = c.id and pa.stage = 'mission_a'
      left join public.bunker_mission_templates ta on ta.id = pa.mission_template_id
      left join public.bunker_team_progress pb
        on pb.run_nonce = v_state.run_nonce and pb.carriage_id = c.id and pb.stage = 'mission_b'
      left join public.bunker_mission_templates tb on tb.id = pb.mission_template_id
      where c.event_id = p_event_id and c.enabled
    ) teams;
  end if;

  return jsonb_build_object(
    'status', 'active',
    'phase', v_state.phase,
    'phaseStartedAt', v_state.phase_started_at,
    'startedAt', v_state.started_at,
    'durationSeconds', v_state.duration_seconds,
    'remainingSeconds', v_remaining,
    'soundEnabled', v_state.sound_enabled,
    'unlocked', v_state.unlocked_at is not null,
    'teams', v_teams,
    'serverNow', v_now
  );
end;
$$;

create or replace function public.owner_begin_bunker_quest(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
  v_guest record;
  v_started timestamptz := clock_timestamp();
begin
  perform public._require_bunker_owner(p_event_id);

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = p_event_id
  for update;

  if v_state.event_id is null or v_state.status <> 'active' or v_state.run_nonce is null then
    raise exception 'bunker emergency must be active first' using errcode = '55000';
  end if;

  if v_state.phase not in ('emergency', 'dossier_1') then
    raise exception 'bunker quest already advanced' using errcode = '55000';
  end if;

  perform public._ensure_bunker_team_progress(p_event_id, v_state.run_nonce);

  for v_guest in
    select g.id from public.guests g where g.event_id = p_event_id
  loop
    perform public._ensure_bunker_guest_profile(p_event_id, v_state.run_nonce, v_guest.id);
  end loop;

  update public.bunker_state
  set phase = 'dossier_1', phase_started_at = v_started, updated_at = now()
  where event_id = p_event_id;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (p_event_id, auth.uid(), 'bunker_quest_started', jsonb_build_object('phase', 'dossier_1'));

  return public.owner_get_bunker_quest(p_event_id);
end;
$$;

create or replace function public.owner_advance_bunker_phase(
  p_event_id uuid,
  p_phase text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
  v_expected text;
  v_required integer := 0;
  v_completed integer := 0;
begin
  perform public._require_bunker_owner(p_event_id);

  select b.* into v_state
  from public.bunker_state b
  where b.event_id = p_event_id
  for update;

  if v_state.event_id is null or v_state.status <> 'active' then
    raise exception 'bunker is not active' using errcode = '55000';
  end if;

  v_expected := case v_state.phase
    when 'dossier_1' then 'dossier_2'
    when 'dossier_2' then 'mission_a'
    when 'mission_a' then 'mission_b'
    when 'mission_b' then 'final'
    when 'final' then 'completed'
    else null
  end;

  if v_expected is null or p_phase <> v_expected then
    raise exception 'invalid bunker phase transition: % -> %', v_state.phase, p_phase using errcode = '22023';
  end if;

  if v_state.phase in ('mission_a', 'mission_b') then
    select count(*)::integer into v_required
    from public.carriages c
    where c.event_id = p_event_id and c.enabled;

    select count(*)::integer into v_completed
    from public.bunker_team_progress p
    where p.event_id = p_event_id
      and p.run_nonce = v_state.run_nonce
      and p.stage = v_state.phase
      and p.completed_at is not null;

    if v_completed < v_required then
      raise exception 'all carriages must complete current bunker mission first' using errcode = '55000';
    end if;
  end if;

  if v_state.phase = 'final' and v_state.unlocked_at is null then
    raise exception 'bunker must be unlocked before completion' using errcode = '55000';
  end if;

  update public.bunker_state
  set phase = p_phase,
      phase_started_at = clock_timestamp(),
      updated_at = now()
  where event_id = p_event_id;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (
    p_event_id,
    auth.uid(),
    'bunker_phase_advanced',
    jsonb_build_object('from', v_state.phase, 'to', p_phase)
  );

  return public.owner_get_bunker_quest(p_event_id);
end;
$$;

create or replace function public.owner_reset_bunker_team_stage(
  p_event_id uuid,
  p_carriage_id uuid,
  p_stage text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
begin
  perform public._require_bunker_owner(p_event_id);

  if p_stage not in ('mission_a', 'mission_b') then
    raise exception 'invalid bunker mission stage' using errcode = '22023';
  end if;

  select b.* into v_state from public.bunker_state b where b.event_id = p_event_id;
  if v_state.run_nonce is null then
    raise exception 'bunker quest not initialized' using errcode = '55000';
  end if;

  update public.bunker_team_progress
  set attempt_count = 0,
      completed_at = null,
      completed_by_guest_id = null,
      updated_at = now()
  where event_id = p_event_id
    and run_nonce = v_state.run_nonce
    and carriage_id = p_carriage_id
    and stage = p_stage;

  return public.owner_get_bunker_quest(p_event_id);
end;
$$;

create or replace function public.owner_force_complete_bunker_team_stage(
  p_event_id uuid,
  p_carriage_id uuid,
  p_stage text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bunker_state%rowtype;
begin
  perform public._require_bunker_owner(p_event_id);

  if p_stage not in ('mission_a', 'mission_b') then
    raise exception 'invalid bunker mission stage' using errcode = '22023';
  end if;

  select b.* into v_state from public.bunker_state b where b.event_id = p_event_id;
  if v_state.run_nonce is null then
    raise exception 'bunker quest not initialized' using errcode = '55000';
  end if;

  update public.bunker_team_progress
  set completed_at = coalesce(completed_at, clock_timestamp()),
      updated_at = now()
  where event_id = p_event_id
    and run_nonce = v_state.run_nonce
    and carriage_id = p_carriage_id
    and stage = p_stage;

  return public.owner_get_bunker_quest(p_event_id);
end;
$$;

create or replace function public.owner_unlock_bunker(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public._require_bunker_owner(p_event_id);

  update public.bunker_state
  set unlocked_at = coalesce(unlocked_at, clock_timestamp()),
      updated_at = now()
  where event_id = p_event_id and status = 'active';

  if not found then
    raise exception 'bunker is not active' using errcode = '55000';
  end if;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (p_event_id, auth.uid(), 'bunker_manual_unlock', '{}'::jsonb);

  return public.owner_get_bunker_quest(p_event_id);
end;
$$;

revoke all on function public._bunker_guest_id(text, text) from public, anon, authenticated;
revoke all on function public._ensure_bunker_guest_profile(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public._ensure_bunker_team_progress(uuid, uuid) from public, anon, authenticated;

revoke all on function public.get_guest_bunker_state(text, text) from public;
revoke all on function public.submit_guest_bunker_mission(text, text, text, text) from public;
revoke all on function public.submit_guest_bunker_final_code(text, text, text) from public;
revoke all on function public.owner_get_bunker_quest(uuid) from public, anon;
revoke all on function public.owner_begin_bunker_quest(uuid) from public, anon;
revoke all on function public.owner_advance_bunker_phase(uuid, text) from public, anon;
revoke all on function public.owner_reset_bunker_team_stage(uuid, uuid, text) from public, anon;
revoke all on function public.owner_force_complete_bunker_team_stage(uuid, uuid, text) from public, anon;
revoke all on function public.owner_unlock_bunker(uuid) from public, anon;

revoke all on function public.owner_start_bunker(uuid, integer) from public, anon;
revoke all on function public.owner_stop_bunker(uuid) from public, anon;
revoke all on function public.owner_get_bunker_control(uuid) from public, anon;
revoke all on function public.get_bunker_screen_state(text) from public;

grant execute on function public.get_guest_bunker_state(text, text) to anon, authenticated;
grant execute on function public.submit_guest_bunker_mission(text, text, text, text) to anon, authenticated;
grant execute on function public.submit_guest_bunker_final_code(text, text, text) to anon, authenticated;
grant execute on function public.owner_get_bunker_quest(uuid) to authenticated;
grant execute on function public.owner_begin_bunker_quest(uuid) to authenticated;
grant execute on function public.owner_advance_bunker_phase(uuid, text) to authenticated;
grant execute on function public.owner_reset_bunker_team_stage(uuid, uuid, text) to authenticated;
grant execute on function public.owner_force_complete_bunker_team_stage(uuid, uuid, text) to authenticated;
grant execute on function public.owner_unlock_bunker(uuid) to authenticated;
grant execute on function public.owner_start_bunker(uuid, integer) to authenticated;
grant execute on function public.owner_stop_bunker(uuid) to authenticated;
grant execute on function public.owner_get_bunker_control(uuid) to authenticated;
grant execute on function public.get_bunker_screen_state(text) to anon, authenticated;