-- M05 «Один шанс»: 90-second route vote and persistent consequences.
create or replace function public._bunker_v2_m05_definition()
returns jsonb language sql immutable security definer set search_path='' as $$
 select jsonb_build_object(
  'title','Один шанс',
  'intro','У вас 90 секунд. Обсудите риск и выберите маршрут вагона. Решение изменит состояние поезда и финальное время.',
  'routes',jsonb_build_array(
    jsonb_build_object('key','A','title','Технический тоннель','description','Короче и быстрее, но путь нестабилен.','risk','Повышенный риск повреждений и скачка питания.'),
    jsonb_build_object('key','B','title','Обходной путь','description','Дольше, зато состояние пути лучше.','risk','Меньше риска, но без временного выигрыша.')
  )
 );
$$;
revoke all on function public._bunker_v2_m05_definition() from public,anon,authenticated;
update public.bunker_mission_instances set definition=definition||public._bunker_v2_m05_definition() where mission_code='MISSION_05' and definition->>'contractVersion'='2';
create or replace function public._bunker_v2_enrich_m05_instance() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.mission_code='MISSION_05' and new.definition->>'contractVersion'='2' then new.definition:=new.definition||public._bunker_v2_m05_definition();end if;return new;end;$$;
revoke all on function public._bunker_v2_enrich_m05_instance() from public,anon,authenticated;
drop trigger if exists bunker_v2_enrich_m05_before_insert on public.bunker_mission_instances;
create trigger bunker_v2_enrich_m05_before_insert before insert on public.bunker_mission_instances for each row execute function public._bunker_v2_enrich_m05_instance();

create or replace function public._bunker_v2_apply_m05_outcome(p_event_id uuid,p_run_nonce uuid,p_carriage_id uuid,p_choice text,p_fallback boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_state public.bunker_wagon_state%rowtype;v_bonus integer;v_damage integer;v_power integer;v_sector boolean;v_result jsonb;
begin
 if p_choice not in ('A','B') then raise exception 'invalid M05 route' using errcode='22023';end if;
 select w.* into v_state from public.bunker_wagon_state w where w.event_id=p_event_id and w.run_nonce=p_run_nonce and w.carriage_id=p_carriage_id for update;
 if v_state.carriage_id is null then raise exception 'M05 wagon state missing' using errcode='55000';end if;
 if v_state.route_choice is not null then
  return jsonb_build_object('routeChoice',v_state.route_choice,'routeBonus',v_state.route_bonus,'trackDamage',v_state.track_damage,'powerInstability',v_state.power_instability,'sector04Found',v_state.sector04_found,'fallback',p_fallback);
 end if;
 if p_choice='A' then v_bonus:=120;v_damage:=20;v_power:=1;v_sector:=true;else v_bonus:=0;v_damage:=5;v_power:=0;v_sector:=false;end if;
 update public.bunker_wagon_state set route_choice=p_choice,route_bonus=route_bonus+v_bonus,track_damage=least(100,track_damage+v_damage),power_instability=power_instability+v_power,sector04_found=sector04_found or v_sector,updated_at=now() where event_id=p_event_id and run_nonce=p_run_nonce and carriage_id=p_carriage_id;
 v_result:=jsonb_build_object('routeChoice',p_choice,'routeBonus',v_bonus,'trackDamage',v_damage,'powerInstability',v_power,'sector04Found',v_sector,'fallback',p_fallback);
 return v_result;
end;$$;
revoke all on function public._bunker_v2_apply_m05_outcome(uuid,uuid,uuid,text,boolean) from public,anon,authenticated;

create or replace function public._submit_bunker_command_m05(p_event_slug text,p_device_key text,p_command_id uuid,p_command_type text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest public.guests%rowtype;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_member public.bunker_mission_members%rowtype;v_profile public.bunker_guest_profiles%rowtype;v_existing public.bunker_command_receipts%rowtype;v_hash text;v_vote text;v_a integer;v_b integer;v_total integer;v_members integer;v_required integer;v_choice text;v_outcome jsonb;v_hint text;v_result jsonb;v_now timestamptz:=clock_timestamp();
begin
 if p_command_id is null or p_payload is null or jsonb_typeof(p_payload)<>'object' then raise exception 'invalid M05 command' using errcode='22023';end if;
 select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then raise exception 'Bunker event not found' using errcode='P0002';end if;
 select g.* into v_guest from public.guests g where g.event_id=v_event_id and g.id=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest.id is null then raise exception 'registered Bunker guest required' using errcode='42501';end if;
 select s.* into v_state from public.bunker_state s where s.event_id=v_event_id for update;if v_state.run_nonce is null then raise exception 'active Bunker V2 run required' using errcode='55000';end if;
 select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then raise exception 'active Bunker V2 run required' using errcode='55000';end if;
 v_hash:=encode(extensions.digest(convert_to(jsonb_build_object('commandType',p_command_type,'payload',p_payload)::text,'UTF8'),'sha256'),'hex');
 select r.* into v_existing from public.bunker_command_receipts r where r.run_nonce=v_state.run_nonce and r.actor_kind='guest' and r.actor_id=v_guest.id and r.command_id=p_command_id;if v_existing.id is not null then if v_existing.request_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='55000';end if;return v_existing.result;end if;
 if v_state.global_game_state<>'MISSION_05' then raise exception 'M05 is not the current Bunker V2 stage' using errcode='55000';end if;
 begin select i.* into v_instance from public.bunker_mission_instances i where i.event_id=v_event_id and i.run_nonce=v_state.run_nonce and i.id=(p_payload->>'instanceId')::uuid for update;exception when invalid_text_representation then raise exception 'invalid M05 instance id' using errcode='22023';end;
 if v_instance.id is null or v_instance.mission_code<>'MISSION_05' or v_instance.scope_key<>v_guest.carriage_id::text then raise exception 'M05 instance does not belong to guest wagon' using errcode='42501';end if;
 if v_instance.status<>'active' then raise exception 'M05 instance is not active' using errcode='55000';end if;
 select m.* into v_member from public.bunker_mission_members m where m.instance_id=v_instance.id and m.guest_id=v_guest.id for update;if v_member.id is null then raise exception 'M05 frozen member required' using errcode='42501';end if;
 select p.* into v_profile from public.bunker_guest_profiles p where p.run_nonce=v_state.run_nonce and p.guest_id=v_guest.id for update;
 if p_command_type='use_ability' then
  if p_payload->>'problemKey'<>'route_choice' or v_profile.special_ability not in ('route_analysis','route_feel','terrain_analysis','map_reconstruction','dangerous_route') or v_profile.ability_uses_remaining<1 then raise exception 'M05 route ability unavailable' using errcode='42501';end if;
  v_hint:=case v_profile.special_ability when 'route_analysis' then 'Маршрут A проходит через служебный технический сектор и даёт выигрыш во времени, но нагрузка на путь выше.' when 'route_feel' then 'Маршрут B заметно мягче для пути. A быстрее, но вагон почувствует удар.' when 'terrain_analysis' then 'Грунт на маршруте B стабильнее. На A возможны повреждения, зато он ведёт к служебному сектору.' when 'map_reconstruction' then 'На старой схеме маршрут A пересекает участок с обозначением «04».' else 'Маршрут A опаснее, но может дать сюжетный фрагмент. Маршрут B безопаснее.' end;
  insert into public.bunker_ability_uses(event_id,run_nonce,instance_id,guest_id,ability_key,problem_key,status,command_id,effect,committed_at) values(v_event_id,v_state.run_nonce,v_instance.id,v_guest.id,v_profile.special_ability,'route_choice','committed',p_command_id,jsonb_build_object('hint',v_hint),v_now);
  update public.bunker_guest_profiles set ability_uses_remaining=ability_uses_remaining-1,ability_used_at=v_now where run_nonce=v_state.run_nonce and guest_id=v_guest.id and ability_uses_remaining>0;if not found then raise exception 'M05 ability changed concurrently' using errcode='40001';end if;
 elsif p_command_type='cast_vote' then
  v_vote:=upper(btrim(p_payload->>'vote'));if v_vote not in ('A','B') then raise exception 'M05 vote must be A or B' using errcode='22023';end if;
  insert into public.bunker_mission_decisions(event_id,run_nonce,instance_id,decision_key,actor_kind,actor_id,actor_scope_key,status,instance_version,command_id,payload,outcome,confirmed_at) values(v_event_id,v_state.run_nonce,v_instance.id,'m05_vote','guest',v_guest.id,v_guest.id::text,'confirmed',v_instance.instance_version,p_command_id,jsonb_build_object('vote',v_vote),jsonb_build_object('vote',v_vote),v_now)
  on conflict(instance_id,decision_key,actor_kind,actor_scope_key) do update set actor_id=excluded.actor_id,command_id=excluded.command_id,payload=excluded.payload,outcome=excluded.outcome,confirmed_at=excluded.confirmed_at;
  select count(*) filter(where d.payload->>'vote'='A')::integer,count(*) filter(where d.payload->>'vote'='B')::integer,count(*)::integer into v_a,v_b,v_total from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m05_vote' and d.status='confirmed';
  select count(*)::integer into v_members from public.bunker_mission_members m where m.instance_id=v_instance.id;v_required:=floor(v_members/2.0)::integer+1;
  if v_a>=v_required or v_b>=v_required or v_total>=v_members then
   v_choice:=case when v_a>v_b then 'A' else 'B' end;
   v_outcome:=public._bunker_v2_apply_m05_outcome(v_event_id,v_state.run_nonce,v_guest.carriage_id,v_choice,false);
   update public.bunker_mission_instances set status='completed',completed_at=v_now,outcome=v_outcome where id=v_instance.id;update public.bunker_mission_members set member_status='completed',updated_at=v_now where instance_id=v_instance.id;
  end if;
 else raise exception 'unsupported M05 command type' using errcode='22023';end if;
 v_result:=jsonb_build_object('contractVersion',2,'status','accepted','commandId',p_command_id,'commandType',p_command_type);insert into public.bunker_command_receipts(event_id,run_nonce,actor_kind,actor_id,command_id,command_type,request_hash,result) values(v_event_id,v_state.run_nonce,'guest',v_guest.id,p_command_id,p_command_type,v_hash,v_result);insert into public.bunker_game_events(event_id,run_nonce,carriage_id,guest_id,event_type,actor_type,actor_id,command_id,correlation_id,instance_id,schema_version,payload) values(v_event_id,v_state.run_nonce,v_guest.carriage_id,v_guest.id,'m05_'||p_command_type,'guest',v_guest.id,p_command_id,p_command_id,v_instance.id,2,jsonb_build_object('missionCode','MISSION_05','commandType',p_command_type));return v_result;
end;$$;
revoke all on function public._submit_bunker_command_m05(text,text,uuid,text,jsonb) from public,anon,authenticated;

create or replace function public._bunker_v2_finalize_m05_on_transition() returns trigger language plpgsql security definer set search_path='' as $$
declare v_instance public.bunker_mission_instances%rowtype;v_carriage uuid;v_outcome jsonb;begin
 if old.global_game_state='MISSION_05' and new.global_game_state='MISSION_06' and old.run_nonce is not null then
  for v_instance in select i.* from public.bunker_mission_instances i where i.event_id=old.event_id and i.run_nonce=old.run_nonce and i.mission_code='MISSION_05' and coalesce(i.outcome->>'routeChoice','')='' order by i.id for update loop
   v_carriage:=v_instance.scope_key::uuid;v_outcome:=public._bunker_v2_apply_m05_outcome(old.event_id,old.run_nonce,v_carriage,'B',true);update public.bunker_mission_instances set status='completed',started_at=coalesce(started_at,clock_timestamp()),completed_at=coalesce(completed_at,clock_timestamp()),outcome=coalesce(outcome,'{}'::jsonb)||v_outcome where id=v_instance.id;update public.bunker_mission_members set member_status='completed',updated_at=now() where instance_id=v_instance.id;
  end loop;
 end if;return new;end;$$;
revoke all on function public._bunker_v2_finalize_m05_on_transition() from public,anon,authenticated;
drop trigger if exists bunker_v2_finalize_m05_on_transition on public.bunker_state;create trigger bunker_v2_finalize_m05_on_transition after update of global_game_state on public.bunker_state for each row execute function public._bunker_v2_finalize_m05_on_transition();

create or replace function public.submit_bunker_command(p_event_slug text,p_device_key text,p_command_id uuid,p_command_type text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest_id uuid;v_state public.bunker_state%rowtype;v_existing public.bunker_command_receipts%rowtype;v_hash text;v_instance_id uuid;begin
 select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then raise exception 'Bunker event not found' using errcode='P0002';end if;v_guest_id:=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest_id is null then raise exception 'registered Bunker guest required' using errcode='42501';end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id for update;if v_state.run_nonce is null then raise exception 'active Bunker V2 run required' using errcode='55000';end if;v_hash:=encode(extensions.digest(convert_to(jsonb_build_object('commandType',p_command_type,'payload',p_payload)::text,'UTF8'),'sha256'),'hex');select r.* into v_existing from public.bunker_command_receipts r where r.run_nonce=v_state.run_nonce and r.actor_kind='guest' and r.actor_id=v_guest_id and r.command_id=p_command_id;if v_existing.id is not null then if v_existing.request_hash<>v_hash then raise exception 'idempotency_conflict' using errcode='55000';end if;return v_existing.result;end if;
 if v_state.global_game_state='MISSION_01' then begin v_instance_id:=(p_payload->>'instanceId')::uuid;exception when others then v_instance_id:=null;end;perform 1 from public.bunker_mission_instances i where i.id=v_instance_id for update;perform 1 from public.bunker_mission_members m where m.instance_id=v_instance_id order by m.id for update;return public._submit_bunker_command_m01(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_02' then return public._submit_bunker_command_m02(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_03' then return public._submit_bunker_command_m03(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_04' then return public._submit_bunker_command_m04(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);elsif v_state.global_game_state='MISSION_05' then return public._submit_bunker_command_m05(p_event_slug,p_device_key,p_command_id,p_command_type,p_payload);end if;raise exception 'Bunker command is unavailable at current stage' using errcode='55000';end;$$;
revoke all on function public.submit_bunker_command(text,text,uuid,text,jsonb) from public,anon,authenticated;grant execute on function public.submit_bunker_command(text,text,uuid,text,jsonb) to anon,authenticated;

create or replace function public.get_guest_bunker_v2_m05(p_event_slug text,p_device_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest public.guests%rowtype;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_profile public.bunker_guest_profiles%rowtype;v_wagon public.carriages%rowtype;v_selected text;v_a integer;v_b integer;v_total integer;v_members integer;v_required integer;v_ability jsonb:=null;v_hint text;v_now timestamptz:=clock_timestamp();begin
 select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select g.* into v_guest from public.guests g where g.event_id=v_event_id and g.id=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest.id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='MISSION_05' and i.scope_key=v_guest.carriage_id::text limit 1;if v_instance.id is null or v_state.global_game_state not in ('MISSION_05','MISSION_06','UNKNOWN_PASSENGER','BREAK_BEFORE_FINAL','FINAL_30','BUNKER_OPEN','FINISHED') then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select p.* into v_profile from public.bunker_guest_profiles p where p.run_nonce=v_state.run_nonce and p.guest_id=v_guest.id;select c.* into v_wagon from public.carriages c where c.id=v_guest.carriage_id;select d.payload->>'vote' into v_selected from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m05_vote' and d.actor_kind='guest' and d.actor_scope_key=v_guest.id::text limit 1;select count(*) filter(where d.payload->>'vote'='A')::integer,count(*) filter(where d.payload->>'vote'='B')::integer,count(*)::integer into v_a,v_b,v_total from public.bunker_mission_decisions d where d.instance_id=v_instance.id and d.decision_key='m05_vote' and d.status='confirmed';select count(*)::integer into v_members from public.bunker_mission_members m where m.instance_id=v_instance.id;v_required:=floor(v_members/2.0)::integer+1;
 if v_profile.special_ability in ('route_analysis','route_feel','terrain_analysis','map_reconstruction','dangerous_route') then select u.effect->>'hint' into v_hint from public.bunker_ability_uses u where u.instance_id=v_instance.id and u.guest_id=v_guest.id and u.problem_key='route_choice' limit 1;v_ability:=jsonb_build_object('available',v_profile.ability_uses_remaining>0 and v_hint is null,'key',v_profile.special_ability,'label',v_profile.ability_description,'hint',coalesce(v_hint,'Можно один раз запросить дополнительный анализ двух маршрутов.'));end if;
 return jsonb_strip_nulls(jsonb_build_object('contractVersion',2,'status',case when v_instance.status='completed' then 'completed' else 'active' end,'serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now),'instanceId',v_instance.id,'instanceVersion',v_instance.instance_version,'title',v_instance.definition->>'title','intro',v_instance.definition->>'intro','wagon',jsonb_build_object('number',v_wagon.number,'label',v_wagon.label),'routes',v_instance.definition->'routes','selectedVote',v_selected,'voteCounts',jsonb_build_object('A',coalesce(v_a,0),'B',coalesce(v_b,0),'total',coalesce(v_total,0),'required',v_required),'ability',v_ability,'outcome',case when v_instance.status='completed' then v_instance.outcome else null end));end;$$;
revoke all on function public.get_guest_bunker_v2_m05(text,text) from public,anon,authenticated;grant execute on function public.get_guest_bunker_v2_m05(text,text) to anon,authenticated;

create or replace function public._bunker_v2_m05_progress(p_event_id uuid,p_run_nonce uuid) returns jsonb language sql stable security definer set search_path='' as $$ select coalesce(jsonb_agg(jsonb_build_object('wagonId',i.scope_key,'label',c.label,'status',case when i.status='completed' then 'completed' else 'active' end,'votesA',(select count(*) from public.bunker_mission_decisions d where d.instance_id=i.id and d.decision_key='m05_vote' and d.payload->>'vote'='A'),'votesB',(select count(*) from public.bunker_mission_decisions d where d.instance_id=i.id and d.decision_key='m05_vote' and d.payload->>'vote'='B'),'required',(select floor(count(*)/2.0)::integer+1 from public.bunker_mission_members m where m.instance_id=i.id),'routeChoice',i.outcome->>'routeChoice') order by c.number),'[]'::jsonb) from public.bunker_mission_instances i join public.carriages c on c.id::text=i.scope_key and c.event_id=p_event_id where i.run_nonce=p_run_nonce and i.mission_code='MISSION_05';$$;
revoke all on function public._bunker_v2_m05_progress(uuid,uuid) from public,anon,authenticated;
create or replace function public.get_bunker_v2_m05_screen(p_event_slug text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event_id uuid;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_deadline timestamptz;v_now timestamptz:=clock_timestamp();begin select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;select max(deadline_at) into v_deadline from public.bunker_mission_instances where run_nonce=v_state.run_nonce and mission_code='MISSION_05';return jsonb_build_object('contractVersion',2,'status',case when v_state.global_game_state='MISSION_05' then 'active' else 'completed' end,'serverNow',v_now,'deadlineAt',coalesce(v_deadline,v_now),'title','Один шанс','wagons',public._bunker_v2_m05_progress(v_event_id,v_state.run_nonce));end;$$;
revoke all on function public.get_bunker_v2_m05_screen(text) from public,anon,authenticated;grant execute on function public.get_bunker_v2_m05_screen(text) to anon,authenticated;
create or replace function public.get_owner_bunker_v2_m05(p_event_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_state public.bunker_state%rowtype;v_deadline timestamptz;v_now timestamptz:=clock_timestamp();begin perform public._require_bunker_owner(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select max(deadline_at) into v_deadline from public.bunker_mission_instances where run_nonce=v_state.run_nonce and mission_code='MISSION_05';return jsonb_build_object('contractVersion',2,'status',case when v_state.global_game_state='MISSION_05' then 'active' else 'completed' end,'serverNow',v_now,'deadlineAt',coalesce(v_deadline,v_now),'title','Один шанс','wagons',public._bunker_v2_m05_progress(p_event_id,v_state.run_nonce));end;$$;
revoke all on function public.get_owner_bunker_v2_m05(uuid) from public,anon,authenticated;grant execute on function public.get_owner_bunker_v2_m05(uuid) to authenticated;
