create extension if not exists pgcrypto with schema extensions;

create table public.events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  wedding_date date not null default date '2026-08-29',
  event_date date not null default date '2026-08-30',
  expected_guest_count integer not null default 40 check (expected_guest_count > 0),
  registration_open boolean not null default true,
  composition_locked boolean not null default false,
  next_ticket_sequence bigint not null default 1 check (next_ticket_sequence > 0),
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.event_state (
  event_id uuid primary key references public.events(id) on delete cascade,
  current_module text not null default 'idle',
  screen_mode text not null default 'idle',
  screen_payload_id uuid,
  screen_payload jsonb,
  screen_pinned boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.carriages (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  number integer not null check (number > 0),
  label text not null,
  accent_hex text not null check (accent_hex ~ '^#[0-9A-Fa-f]{6}$'),
  visual_mark text not null,
  sort_order integer not null,
  enabled boolean not null default true,
  unique (event_id, number),
  unique (event_id, sort_order)
);

create table public.guests (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  first_name text not null check (length(btrim(first_name)) > 0),
  last_name text not null check (length(btrim(last_name)) > 0),
  affiliation_type text not null check (
    affiliation_type in ('liza', 'viktor', 'common', 'family', 'colleagues', 'other')
  ),
  affiliation_detail text,
  carriage_id uuid not null references public.carriages(id) on delete restrict,
  ticket_sequence bigint not null check (ticket_sequence > 0),
  ticket_number text not null,
  registered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (event_id, ticket_sequence),
  unique (event_id, ticket_number)
);

create table public.guest_device_bindings (
  event_id uuid not null references public.events(id) on delete cascade,
  guest_id uuid not null references public.guests(id) on delete cascade,
  device_key_hash text not null,
  created_at timestamptz not null default now(),
  primary key (event_id, device_key_hash),
  unique (event_id, guest_id)
);

create table public.guest_recovery_codes (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  guest_id uuid not null references public.guests(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.owner_action_log (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.carriage_calls (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  message text not null check (length(btrim(message)) > 0),
  active boolean not null default true,
  show_on_screen boolean not null default false,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  cleared_at timestamptz
);

create table public.carriage_call_targets (
  call_id uuid not null references public.carriage_calls(id) on delete cascade,
  carriage_id uuid not null references public.carriages(id) on delete cascade,
  primary key (call_id, carriage_id)
);

create index guests_event_carriage_idx on public.guests(event_id, carriage_id);
create index guests_event_affiliation_idx on public.guests(event_id, affiliation_type);
create index guests_event_name_idx on public.guests(event_id, lower(first_name), lower(last_name));
create index carriage_calls_event_active_idx on public.carriage_calls(event_id, active) where active;

alter table public.events enable row level security;
alter table public.event_state enable row level security;
alter table public.carriages enable row level security;
alter table public.guests enable row level security;
alter table public.guest_device_bindings enable row level security;
alter table public.guest_recovery_codes enable row level security;
alter table public.owner_action_log enable row level security;
alter table public.carriage_calls enable row level security;
alter table public.carriage_call_targets enable row level security;

create policy "owner reads own events"
on public.events for select to authenticated
using (owner_user_id = auth.uid());

create policy "owner updates own events"
on public.events for update to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

create policy "owner reads own event state"
on public.event_state for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = event_state.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner updates own event state"
on public.event_state for update to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = event_state.event_id and e.owner_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.events e
    where e.id = event_state.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads own carriages"
on public.carriages for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = carriages.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner manages own carriages"
on public.carriages for all to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = carriages.event_id and e.owner_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.events e
    where e.id = carriages.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads all guests"
on public.guests for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = guests.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner manages guests"
on public.guests for all to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = guests.event_id and e.owner_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.events e
    where e.id = guests.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads device bindings"
on public.guest_device_bindings for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = guest_device_bindings.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads recovery codes"
on public.guest_recovery_codes for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = guest_recovery_codes.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads own action log"
on public.owner_action_log for select to authenticated
using (owner_user_id = auth.uid());

create policy "owner reads carriage calls"
on public.carriage_calls for select to authenticated
using (
  exists (
    select 1 from public.events e
    where e.id = carriage_calls.event_id and e.owner_user_id = auth.uid()
  )
);

create policy "owner reads carriage call targets"
on public.carriage_call_targets for select to authenticated
using (
  exists (
    select 1
    from public.carriage_calls cc
    join public.events e on e.id = cc.event_id
    where cc.id = carriage_call_targets.call_id and e.owner_user_id = auth.uid()
  )
);

create or replace function public._normalize_spaces(value text)
returns text
language sql
immutable
set search_path = public
as $$
  select regexp_replace(btrim(coalesce(value, '')), '\s+', ' ', 'g');
$$;

create or replace function public._device_hash(device_key text)
returns text
language sql
immutable
set search_path = public, extensions
as $$
  select encode(extensions.digest(coalesce(device_key, ''), 'sha256'), 'hex');
$$;

create or replace function public._guest_profile_json(guest_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', g.id,
    'firstName', g.first_name,
    'lastName', g.last_name,
    'affiliationType', g.affiliation_type,
    'affiliationDetail', coalesce(g.affiliation_detail, ''),
    'ticketNumber', g.ticket_number,
    'carriage', jsonb_build_object(
      'id', c.id,
      'number', c.number,
      'label', c.label,
      'accentHex', c.accent_hex,
      'visualMark', c.visual_mark
    )
  )
  from public.guests g
  join public.carriages c on c.id = g.carriage_id
  where g.id = guest_id;
$$;

create or replace function public.owner_create_event(
  p_slug text,
  p_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid := auth.uid();
  v_event_id uuid;
begin
  if v_owner is null then
    raise exception 'owner authentication required' using errcode = '42501';
  end if;

  insert into public.events(slug, name, owner_user_id)
  values (public._normalize_spaces(p_slug), public._normalize_spaces(p_name), v_owner)
  returning id into v_event_id;

  insert into public.event_state(event_id) values (v_event_id);

  insert into public.carriages(event_id, number, label, accent_hex, visual_mark, sort_order)
  values
    (v_event_id, 1, 'ВАГОН №1', '#31483A', '01', 1),
    (v_event_id, 2, 'ВАГОН №2', '#9A6348', '02', 2),
    (v_event_id, 3, 'ВАГОН №3', '#7E3F3C', '03', 3),
    (v_event_id, 4, 'ВАГОН №4', '#78806A', '04', 4),
    (v_event_id, 5, 'ВАГОН №5', '#B49B7E', '05', 5);

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (v_event_id, v_owner, 'event_created', jsonb_build_object('slug', p_slug));

  return jsonb_build_object('id', v_event_id, 'slug', public._normalize_spaces(p_slug));
end;
$$;

create or replace function public.restore_guest(
  p_event_slug text,
  p_device_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
  v_guest_id uuid;
  v_hash text;
begin
  if length(coalesce(p_device_key, '')) < 8 then
    return jsonb_build_object('status', 'not_found');
  end if;

  select id into v_event_id
  from public.events
  where slug = public._normalize_spaces(p_event_slug);

  if v_event_id is null then
    return jsonb_build_object('status', 'not_found');
  end if;

  v_hash := public._device_hash(p_device_key);

  select guest_id into v_guest_id
  from public.guest_device_bindings
  where event_id = v_event_id and device_key_hash = v_hash;

  if v_guest_id is null then
    return jsonb_build_object('status', 'not_found');
  end if;

  update public.guests
  set last_seen_at = now()
  where id = v_guest_id;

  return jsonb_build_object(
    'status', 'restored',
    'guest', public._guest_profile_json(v_guest_id)
  );
end;
$$;

create or replace function public.register_guest(
  p_event_slug text,
  p_device_key text,
  p_first_name text,
  p_last_name text,
  p_affiliation_type text,
  p_affiliation_detail text default null,
  p_confirm_duplicate boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.events%rowtype;
  v_hash text;
  v_existing_guest_id uuid;
  v_duplicate_guest_id uuid;
  v_carriage_id uuid;
  v_ticket_sequence bigint;
  v_ticket_number text;
  v_guest_id uuid;
  v_first_name text := public._normalize_spaces(p_first_name);
  v_last_name text := public._normalize_spaces(p_last_name);
  v_detail text := nullif(public._normalize_spaces(p_affiliation_detail), '');
begin
  if length(coalesce(p_device_key, '')) < 8 then
    raise exception 'invalid device key' using errcode = '22023';
  end if;
  if v_first_name = '' then
    raise exception 'first name is required' using errcode = '22023';
  end if;
  if v_last_name = '' then
    raise exception 'last name is required' using errcode = '22023';
  end if;
  if p_affiliation_type not in ('liza', 'viktor', 'common', 'family', 'colleagues', 'other') then
    raise exception 'invalid affiliation type' using errcode = '22023';
  end if;

  select * into v_event
  from public.events
  where slug = public._normalize_spaces(p_event_slug)
  for update;

  if v_event.id is null then
    raise exception 'event not found' using errcode = 'P0002';
  end if;

  v_hash := public._device_hash(p_device_key);

  select guest_id into v_existing_guest_id
  from public.guest_device_bindings
  where event_id = v_event.id and device_key_hash = v_hash;

  if v_existing_guest_id is not null then
    update public.guests set last_seen_at = now() where id = v_existing_guest_id;
    return jsonb_build_object(
      'status', 'restored',
      'guest', public._guest_profile_json(v_existing_guest_id)
    );
  end if;

  if not v_event.registration_open then
    raise exception 'registration is closed' using errcode = '55000';
  end if;

  if not p_confirm_duplicate then
    select id into v_duplicate_guest_id
    from public.guests
    where event_id = v_event.id
      and lower(first_name) = lower(v_first_name)
      and lower(last_name) = lower(v_last_name)
    limit 1;

    if v_duplicate_guest_id is not null then
      return jsonb_build_object(
        'status', 'duplicate_warning',
        'publicName', v_first_name || ' ' || upper(left(v_last_name, 1)) || '.'
      );
    end if;
  end if;

  select c.id into v_carriage_id
  from public.carriages c
  left join public.guests g on g.carriage_id = c.id and g.event_id = v_event.id
  where c.event_id = v_event.id and c.enabled
  group by c.id, c.sort_order
  order by
    count(g.id) asc,
    count(g.id) filter (where g.affiliation_type = p_affiliation_type) asc,
    random()
  limit 1;

  if v_carriage_id is null then
    raise exception 'no enabled carriages available' using errcode = '55000';
  end if;

  v_ticket_sequence := v_event.next_ticket_sequence;
  update public.events
  set next_ticket_sequence = next_ticket_sequence + 1
  where id = v_event.id;

  v_ticket_number := 'LV-' || lpad(v_ticket_sequence::text, 3, '0');

  insert into public.guests(
    event_id,
    first_name,
    last_name,
    affiliation_type,
    affiliation_detail,
    carriage_id,
    ticket_sequence,
    ticket_number
  )
  values (
    v_event.id,
    v_first_name,
    v_last_name,
    p_affiliation_type,
    v_detail,
    v_carriage_id,
    v_ticket_sequence,
    v_ticket_number
  )
  returning id into v_guest_id;

  insert into public.guest_device_bindings(event_id, guest_id, device_key_hash)
  values (v_event.id, v_guest_id, v_hash);

  return jsonb_build_object(
    'status', 'registered',
    'guest', public._guest_profile_json(v_guest_id)
  );
end;
$$;

create or replace function public.owner_reassign_guest(
  p_guest_id uuid,
  p_carriage_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid := auth.uid();
  v_event_id uuid;
  v_old_carriage_id uuid;
begin
  select g.event_id, g.carriage_id
  into v_event_id, v_old_carriage_id
  from public.guests g
  join public.events e on e.id = g.event_id
  where g.id = p_guest_id and e.owner_user_id = v_owner;

  if v_event_id is null then
    raise exception 'owner access required' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.carriages c
    where c.id = p_carriage_id and c.event_id = v_event_id and c.enabled
  ) then
    raise exception 'invalid carriage for event' using errcode = '22023';
  end if;

  update public.guests
  set carriage_id = p_carriage_id
  where id = p_guest_id;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (
    v_event_id,
    v_owner,
    'guest_reassigned',
    jsonb_build_object(
      'guestId', p_guest_id,
      'fromCarriageId', v_old_carriage_id,
      'toCarriageId', p_carriage_id
    )
  );

  return jsonb_build_object('status', 'updated', 'guest', public._guest_profile_json(p_guest_id));
end;
$$;

create or replace function public.owner_delete_guest(p_guest_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid := auth.uid();
  v_event_id uuid;
begin
  select g.event_id into v_event_id
  from public.guests g
  join public.events e on e.id = g.event_id
  where g.id = p_guest_id and e.owner_user_id = v_owner;

  if v_event_id is null then
    raise exception 'owner access required' using errcode = '42501';
  end if;

  insert into public.owner_action_log(event_id, owner_user_id, action, payload)
  values (v_event_id, v_owner, 'guest_deleted', jsonb_build_object('guestId', p_guest_id));

  delete from public.guests where id = p_guest_id;
  return jsonb_build_object('status', 'deleted', 'guestId', p_guest_id);
end;
$$;

create or replace function public.owner_lock_composition(p_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner uuid := auth.uid();
begin
  update public.events
  set composition_locked = true
  where id = p_event_id and owner_user_id = v_owner;

  if not found then
    raise exception 'owner access required' using errcode = '42501';
  end if;

  insert into public.owner_action_log(event_id, owner_user_id, action)
  values (p_event_id, v_owner, 'composition_locked');

  return jsonb_build_object('status', 'locked', 'registrationOpen', true);
end;
$$;

revoke all on function public._normalize_spaces(text) from public;
revoke all on function public._device_hash(text) from public;
revoke all on function public._guest_profile_json(uuid) from public;

revoke all on function public.owner_create_event(text, text) from public;
revoke all on function public.restore_guest(text, text) from public;
revoke all on function public.register_guest(text, text, text, text, text, text, boolean) from public;
revoke all on function public.owner_reassign_guest(uuid, uuid) from public;
revoke all on function public.owner_delete_guest(uuid) from public;
revoke all on function public.owner_lock_composition(uuid) from public;

grant execute on function public.owner_create_event(text, text) to authenticated;
grant execute on function public.restore_guest(text, text) to anon, authenticated;
grant execute on function public.register_guest(text, text, text, text, text, text, boolean) to anon, authenticated;
grant execute on function public.owner_reassign_guest(uuid, uuid) to authenticated;
grant execute on function public.owner_delete_guest(uuid) to authenticated;
grant execute on function public.owner_lock_composition(uuid) to authenticated;
