-- UNKNOWN_PASSENGER story beat. It is also the no-dead-end recovery bridge into the final.
create or replace function public._bunker_v2_unknown_passenger_transition()
returns trigger language plpgsql security definer set search_path='' as $$
declare v_contract integer;v_instance public.bunker_mission_instances%rowtype;v_sector text;v_code text;v_entry uuid;v_m06_success boolean;v_now timestamptz:=clock_timestamp();begin
 if new.run_nonce is null then return new;end if;select r.contract_version into v_contract from public.bunker_game_runs r where r.event_id=new.event_id and r.run_nonce=new.run_nonce;if v_contract is distinct from 2 then return new;end if;
 if old.global_game_state is distinct from new.global_game_state and new.global_game_state='UNKNOWN_PASSENGER' then
  select i.* into v_instance from public.bunker_mission_instances i where i.event_id=new.event_id and i.run_nonce=new.run_nonce and i.mission_code='UNKNOWN_PASSENGER' limit 1 for update;
  select p.canonical_value into v_sector from public.bunker_final_parameters p where p.event_id=new.event_id and p.run_nonce=new.run_nonce and p.parameter_key='sector';select p.canonical_value into v_code from public.bunker_final_parameters p where p.event_id=new.event_id and p.run_nonce=new.run_nonce and p.parameter_key='access_code';
  select exists(select 1 from public.bunker_mission_instances i where i.event_id=new.event_id and i.run_nonce=new.run_nonce and i.mission_code='MISSION_06' and i.outcome->>'status'='success') into v_m06_success;
  update public.bunker_state set bunker_revealed=true where event_id=new.event_id;
  update public.bunker_mission_instances set started_at=coalesce(started_at,v_now),deadline_at=coalesce(deadline_at,v_now+interval '60 seconds'),definition=definition||jsonb_build_object('title','Неизвестный пассажир') where id=v_instance.id;
  update public.bunker_final_parameters set status='resolved',source_kind=case when v_m06_success then coalesce(source_kind,'mission06') else 'unknown_passenger' end,source_instance_id=case when v_m06_success and source_instance_id is not null then source_instance_id else v_instance.id end,public_hint=jsonb_build_object('source','Досье BK-17'),resolved_at=coalesce(resolved_at,v_now) where event_id=new.event_id and run_nonce=new.run_nonce and parameter_key in ('sector','access_code');
  select a.id into v_entry from public.bunker_archive_entries a where a.run_nonce=new.run_nonce and a.artifact_key='UNKNOWN-BK17' limit 1;if v_entry is null then insert into public.bunker_archive_entries(event_id,run_nonce,carriage_id,artifact_key,content_type,content,decryption_status,decoded_at) values(new.event_id,new.run_nonce,null,'UNKNOWN-BK17','document',jsonb_build_object('title','Неизвестный пассажир','dossierId','BK-17','sector',v_sector,'accessCode',v_code,'summary','Досье отсутствует в официальном списке пассажиров и связано с защищённым объектом.'),'decoded',v_now) returning id into v_entry;end if;insert into public.bunker_archive_entitlements(event_id,run_nonce,archive_entry_id,carriage_id,owner_scope_kind,owner_scope_key,status) values(new.event_id,new.run_nonce,v_entry,null,'global','global','active') on conflict(run_nonce,archive_entry_id,owner_scope_kind,owner_scope_key) do nothing;
 elsif old.global_game_state='UNKNOWN_PASSENGER' and new.global_game_state='BREAK_BEFORE_FINAL' then
  update public.bunker_mission_instances set outcome=coalesce(outcome,'{}'::jsonb)||jsonb_build_object('status','revealed','bunkerRevealed',true),completed_at=coalesce(completed_at,v_now) where event_id=new.event_id and run_nonce=new.run_nonce and mission_code='UNKNOWN_PASSENGER';
 end if;return new;end;$$;
revoke all on function public._bunker_v2_unknown_passenger_transition() from public,anon,authenticated;drop trigger if exists bunker_v2_unknown_passenger_transition on public.bunker_state;create trigger bunker_v2_unknown_passenger_transition after update of global_game_state on public.bunker_state for each row execute function public._bunker_v2_unknown_passenger_transition();

create or replace function public.get_guest_bunker_v2_unknown_passenger(p_event_slug text,p_device_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event_id uuid;v_guest uuid;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_sector text;v_code text;v_m06 boolean;v_now timestamptz:=clock_timestamp();begin select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;v_guest:=public._bunker_guest_id(p_event_slug,p_device_key);if v_guest is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;if v_state.global_game_state <> 'UNKNOWN_PASSENGER' then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='UNKNOWN_PASSENGER' limit 1;select canonical_value into v_sector from public.bunker_final_parameters where run_nonce=v_state.run_nonce and parameter_key='sector';select canonical_value into v_code from public.bunker_final_parameters where run_nonce=v_state.run_nonce and parameter_key='access_code';select exists(select 1 from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='MISSION_06' and i.outcome->>'status'='success') into v_m06;return jsonb_build_object('contractVersion',2,'status','active','serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now+interval '60 seconds'),'title','Неизвестный пассажир','dossierId','BK-17','lead','В архиве найдено досье пассажира, которого нет в официальном списке состава.','sector',v_sector,'accessCode',v_code,'bunkerRevealed',v_state.bunker_revealed,'recoveredBy',case when v_m06 then 'common_protocol' else 'archive_recovery' end,'storyPoints',jsonb_build_array('BK-17 связан с закрытым подземным объектом.','Маршрут поезда был изменён не случайно.','Безопасная точка подтверждена и данные доступа сохранены в архиве.'));end;$$;
revoke all on function public.get_guest_bunker_v2_unknown_passenger(text,text) from public,anon,authenticated;grant execute on function public.get_guest_bunker_v2_unknown_passenger(text,text) to anon,authenticated;

create or replace function public.get_bunker_v2_unknown_passenger_screen(p_event_slug text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event_id uuid;v_state public.bunker_state%rowtype;v_run public.bunker_game_runs%rowtype;v_instance public.bunker_mission_instances%rowtype;v_sector text;v_now timestamptz:=clock_timestamp();begin select e.id into v_event_id from public.events e where e.slug=public._normalize_spaces(p_event_slug);if v_event_id is null then return jsonb_build_object('contractVersion',2,'status','not_found','serverNow',v_now);end if;select s.* into v_state from public.bunker_state s where s.event_id=v_event_id;if v_state.run_nonce is null then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select r.* into v_run from public.bunker_game_runs r where r.event_id=v_event_id and r.run_nonce=v_state.run_nonce;if v_run.contract_version<>2 then return jsonb_build_object('contractVersion',2,'status','legacy','serverNow',v_now);end if;if v_state.global_game_state<>'UNKNOWN_PASSENGER' then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='UNKNOWN_PASSENGER' limit 1;select canonical_value into v_sector from public.bunker_final_parameters where run_nonce=v_state.run_nonce and parameter_key='sector';return jsonb_build_object('contractVersion',2,'status','active','serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now+interval '60 seconds'),'title','Неизвестный пассажир','dossierId','BK-17','sector',v_sector);end;$$;
revoke all on function public.get_bunker_v2_unknown_passenger_screen(text) from public,anon,authenticated;grant execute on function public.get_bunker_v2_unknown_passenger_screen(text) to anon,authenticated;
create or replace function public.get_owner_bunker_v2_unknown_passenger(p_event_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_state public.bunker_state%rowtype;v_instance public.bunker_mission_instances%rowtype;v_sector text;v_now timestamptz:=clock_timestamp();begin perform public._require_bunker_owner(p_event_id);select s.* into v_state from public.bunker_state s where s.event_id=p_event_id;if v_state.run_nonce is null or v_state.global_game_state<>'UNKNOWN_PASSENGER' then return jsonb_build_object('contractVersion',2,'status','idle','serverNow',v_now);end if;select i.* into v_instance from public.bunker_mission_instances i where i.run_nonce=v_state.run_nonce and i.mission_code='UNKNOWN_PASSENGER' limit 1;select canonical_value into v_sector from public.bunker_final_parameters where run_nonce=v_state.run_nonce and parameter_key='sector';return jsonb_build_object('contractVersion',2,'status','active','serverNow',v_now,'deadlineAt',coalesce(v_instance.deadline_at,v_now+interval '60 seconds'),'title','Неизвестный пассажир','dossierId','BK-17','sector',v_sector);end;$$;
revoke all on function public.get_owner_bunker_v2_unknown_passenger(uuid) from public,anon,authenticated;grant execute on function public.get_owner_bunker_v2_unknown_passenger(uuid) to authenticated;
