import { submitBunkerCommand, throwBunkerV2RpcError, type BunkerV2RpcClient } from './command.service';
import type { BunkerCommandReceipt } from './contracts';

export type FinalRpcClient = BunkerV2RpcClient;
export type FinalParameter = 'coordinates'|'sector'|'access_code'|'gate_time'|'password';
export type FinalFragment = { parameter: FinalParameter; label: string; part: number; totalParts: number; value: string };
export type FinalValues = { coordinates:string;sector:string;accessCode:string;gateTime:string;password:string };
export type FinalHint = { level:number;text:string };
export type FinalGuestReadModel =
  | { contractVersion:2;status:'idle'|'legacy'|'not_found';serverNow:string }
  | { contractVersion:2;status:'active'|'completed';serverNow:string;deadlineAt:string;title:string;instanceId:string;wagon:{number:number;label:string};fragments:FinalFragment[];terminal:{solved:number;total:number;wrongAttempts:number;unlocked:boolean};hint:FinalHint;timeAdjustmentSeconds:number };
export type FinalScreenReadModel =
  | { contractVersion:2;status:'idle'|'legacy'|'not_found';serverNow:string }
  | { contractVersion:2;status:'active'|'completed';serverNow:string;deadlineAt:string;solved:number;total:number;wrongAttempts:number;unlocked:boolean;hintLevel:number;timeAdjustmentSeconds:number };
export type FinalOwnerReadModel = FinalScreenReadModel;

function obj(v:unknown,l:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(`Unexpected final ${l}`);return v as Record<string,unknown>;}function text(v:unknown,l:string){if(typeof v!=='string'||!v.trim())throw new Error(`Unexpected final ${l}`);return v;}function int(v:unknown,l:string){if(typeof v!=='number'||!Number.isInteger(v))throw new Error(`Unexpected final ${l}`);return v;}function time(v:unknown){const s=text(v,'timestamp');if(!Number.isFinite(Date.parse(s)))throw new Error('Unexpected final timestamp');return s;}
const PARAMETERS=new Set<FinalParameter>(['coordinates','sector','access_code','gate_time','password']);
export function parseFinalGuestReadModel(value:unknown):FinalGuestReadModel{const r=obj(value,'read model');if(r.contractVersion!==2||typeof r.status!=='string')throw new Error('Unexpected final read model');if(r.status==='idle'||r.status==='legacy'||r.status==='not_found')return{contractVersion:2,status:r.status,serverNow:time(r.serverNow)};if(r.status!=='active'&&r.status!=='completed')throw new Error('Unexpected final status');if(!Array.isArray(r.fragments))throw new Error('Unexpected final fragments');const wagon=obj(r.wagon,'wagon'),terminal=obj(r.terminal,'terminal'),hint=obj(r.hint,'hint');return{contractVersion:2,status:r.status,serverNow:time(r.serverNow),deadlineAt:time(r.deadlineAt),title:text(r.title,'title'),instanceId:text(r.instanceId,'instance'),wagon:{number:int(wagon.number,'wagon number'),label:text(wagon.label,'wagon label')},fragments:r.fragments.map(v=>{const f=obj(v,'fragment'),parameter=text(f.parameter,'parameter') as FinalParameter;if(!PARAMETERS.has(parameter))throw new Error('Unexpected final parameter');return{parameter,label:text(f.label,'fragment label'),part:int(f.part,'part'),totalParts:int(f.totalParts,'total parts'),value:text(f.value,'fragment value')};}),terminal:{solved:int(terminal.solved,'solved'),total:int(terminal.total,'total'),wrongAttempts:int(terminal.wrongAttempts,'wrong attempts'),unlocked:Boolean(terminal.unlocked)},hint:{level:int(hint.level,'hint level'),text:typeof hint.text==='string'?hint.text:''},timeAdjustmentSeconds:int(r.timeAdjustmentSeconds,'time adjustment')};}
export async function getGuestFinalReadModel(client:FinalRpcClient,eventSlug:string,deviceKey:string){const{data,error}=await client.rpc('get_guest_bunker_v2_final',{p_event_slug:eventSlug,p_device_key:deviceKey});if(error)throwBunkerV2RpcError(error,'Final read failed');return parseFinalGuestReadModel(data);}
export async function getFinalScreenReadModel(client:FinalRpcClient,eventSlug:string){const{data,error}=await client.rpc('get_bunker_v2_final_screen',{p_event_slug:eventSlug});if(error)throwBunkerV2RpcError(error,'Final screen read failed');return data as FinalScreenReadModel;}
export async function getOwnerFinalReadModel(client:FinalRpcClient,eventId:string){const{data,error}=await client.rpc('get_owner_bunker_v2_final',{p_event_id:eventId});if(error)throwBunkerV2RpcError(error,'Final owner read failed');return data as FinalOwnerReadModel;}
export function requestFinalAccess(client:FinalRpcClient,input:{eventSlug:string;deviceKey:string;commandId:string;values:FinalValues}):Promise<BunkerCommandReceipt>{const values=input.values;if(Object.values(values).some(v=>!v.trim()))return Promise.reject(new Error('All five final fields are required'));return submitBunkerCommand(client,input.eventSlug,input.deviceKey,input.commandId,{type:'request_access',payload:{coordinates:values.coordinates,sector:values.sector,accessCode:values.accessCode,gateTime:values.gateTime,password:values.password}});}
async function owner(client:FinalRpcClient,name:string,args:Record<string,unknown>){const{data,error}=await client.rpc(name,args);if(error)throwBunkerV2RpcError(error,'Final owner command failed');return data;}
export function addFinalTime(client:FinalRpcClient,eventId:string,seconds=120){return owner(client,'owner_bunker_v2_add_final_time',{p_event_id:eventId,p_seconds:seconds});}
export function giveFinalHint(client:FinalRpcClient,eventId:string){return owner(client,'owner_bunker_v2_final_hint',{p_event_id:eventId});}
export function emergencyOpenFinal(client:FinalRpcClient,eventId:string){return owner(client,'owner_bunker_v2_emergency_open',{p_event_id:eventId});}
