import { submitBunkerCommand, throwBunkerV2RpcError, type BunkerV2RpcClient } from './command.service';
import type { BunkerCommandReceipt } from './contracts';
export type MissionSixRpcClient = BunkerV2RpcClient;
export type MissionSixFragment = { key:string; label:string; body:string };
export type MissionSixOption = { key:'A'|'B'|'C'; title:string; summary:string };
export type MissionSixConsensus = { wagonId:string; label:string; votesA:number; votesB:number; votesC:number; required:number; consensus:'A'|'B'|'C'|null };
export type MissionSixOutcome = { status:'success'; protocol:'B'; sector:'04'; accessCode:'4719' };
export type MissionSixGuestReadModel =
 | { contractVersion:2; status:'idle'|'legacy'|'not_found'; serverNow:string }
 | { contractVersion:2; status:'active'|'completed'; serverNow:string; deadlineAt:string; instanceId:string; instanceVersion:number; title:string; intro:string; viewer:{wagonId:string;wagonNumber:number;canVote:boolean}; privateFragment:MissionSixFragment; fragmentShared:boolean; revealedFragments:MissionSixFragment[]; fragmentsRevealed:number; fragmentsTotal:number; options:MissionSixOption[]; selectedVote:'A'|'B'|'C'|null; wagonConsensus:MissionSixConsensus[]; ability:{available:boolean;key:string;label:string;hint:string}|null; outcome?:MissionSixOutcome };
export type MissionSixScreenReadModel =
 | { contractVersion:2; status:'idle'|'legacy'|'not_found'; serverNow:string }
 | { contractVersion:2; status:'active'|'completed'; serverNow:string; deadlineAt:string; title:string; fragmentsRevealed:number; fragmentsTotal:number; wagons:Array<{wagonId:string;label:string;consensusReady:boolean}> };
export type MissionSixOwnerReadModel = MissionSixScreenReadModel;
function obj(v:unknown,l:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(`Unexpected mission six ${l}`);return v as Record<string,unknown>;}function text(v:unknown,l:string){if(typeof v!=='string'||!v.trim())throw new Error(`Unexpected mission six ${l}`);return v;}function int(v:unknown,l:string){if(typeof v!=='number'||!Number.isInteger(v)||v<0)throw new Error(`Unexpected mission six ${l}`);return v;}function time(v:unknown){const x=text(v,'timestamp');if(!Number.isFinite(Date.parse(x)))throw new Error('Unexpected mission six timestamp');return x;}function fragment(v:unknown):MissionSixFragment{const x=obj(v,'fragment');return{key:text(x.key,'fragment key'),label:text(x.label,'fragment label'),body:text(x.body,'fragment body')}}function option(v:unknown):MissionSixOption{const x=obj(v,'option');if(x.key!=='A'&&x.key!=='B'&&x.key!=='C')throw new Error('Unexpected mission six option');return{key:x.key,title:text(x.title,'option title'),summary:text(x.summary,'option summary')}}
export function parseMissionSixGuestReadModel(value:unknown):MissionSixGuestReadModel{const r=obj(value,'read model');if(r.contractVersion!==2||typeof r.status!=='string')throw new Error('Unexpected mission six read model');if(r.status==='idle'||r.status==='legacy'||r.status==='not_found')return{contractVersion:2,status:r.status,serverNow:time(r.serverNow)};if(r.status!=='active'&&r.status!=='completed')throw new Error('Unexpected mission six status');const viewer=obj(r.viewer,'viewer');if(!Array.isArray(r.revealedFragments)||!Array.isArray(r.options)||r.options.length!==3||!Array.isArray(r.wagonConsensus))throw new Error('Unexpected mission six payload');const selected=r.selectedVote==='A'||r.selectedVote==='B'||r.selectedVote==='C'?r.selectedVote:null;const ability=r.ability===null?null:(()=>{const a=obj(r.ability,'ability');return{available:Boolean(a.available),key:text(a.key,'ability key'),label:text(a.label,'ability label'),hint:text(a.hint,'ability hint')}})();const outcome=r.outcome===undefined||r.outcome===null?undefined:(()=>{const o=obj(r.outcome,'outcome');if(o.status!=='success'||o.protocol!=='B'||o.sector!=='04'||o.accessCode!=='4719')throw new Error('Unexpected mission six outcome');return{status:'success' as const,protocol:'B' as const,sector:'04' as const,accessCode:'4719' as const};})();return{contractVersion:2,status:r.status,serverNow:time(r.serverNow),deadlineAt:time(r.deadlineAt),instanceId:text(r.instanceId,'instance'),instanceVersion:int(r.instanceVersion,'version'),title:text(r.title,'title'),intro:text(r.intro,'intro'),viewer:{wagonId:text(viewer.wagonId,'wagon id'),wagonNumber:int(viewer.wagonNumber,'wagon number'),canVote:Boolean(viewer.canVote)},privateFragment:fragment(r.privateFragment),fragmentShared:Boolean(r.fragmentShared),revealedFragments:r.revealedFragments.map(fragment),fragmentsRevealed:int(r.fragmentsRevealed,'fragments revealed'),fragmentsTotal:int(r.fragmentsTotal,'fragments total'),options:r.options.map(option),selectedVote:selected,wagonConsensus:r.wagonConsensus.map(v=>{const c=obj(v,'consensus'),consensus=c.consensus==='A'||c.consensus==='B'||c.consensus==='C'?c.consensus:null;return{wagonId:text(c.wagonId,'wagon id'),label:text(c.label,'wagon label'),votesA:int(c.votesA,'votes A'),votesB:int(c.votesB,'votes B'),votesC:int(c.votesC,'votes C'),required:int(c.required,'required'),consensus}}),ability,...(outcome?{outcome}:{})};}
export async function getGuestMissionSixReadModel(client:MissionSixRpcClient,eventSlug:string,deviceKey:string){const{data,error}=await client.rpc('get_guest_bunker_v2_m06',{p_event_slug:eventSlug,p_device_key:deviceKey});if(error)throwBunkerV2RpcError(error,'Mission six read failed');return parseMissionSixGuestReadModel(data);}export async function getMissionSixScreenReadModel(client:MissionSixRpcClient,eventSlug:string){const{data,error}=await client.rpc('get_bunker_v2_m06_screen',{p_event_slug:eventSlug});if(error)throwBunkerV2RpcError(error,'Mission six screen failed');return data as MissionSixScreenReadModel;}export async function getOwnerMissionSixReadModel(client:MissionSixRpcClient,eventId:string){const{data,error}=await client.rpc('get_owner_bunker_v2_m06',{p_event_id:eventId});if(error)throwBunkerV2RpcError(error,'Mission six owner failed');return data as MissionSixOwnerReadModel;}
export function revealMissionSixFragment(client:MissionSixRpcClient,input:{eventSlug:string;deviceKey:string;commandId:string;instanceId:string;fragmentKey:string}):Promise<BunkerCommandReceipt>{return submitBunkerCommand(client,input.eventSlug,input.deviceKey,input.commandId,{type:'reveal_fragment',payload:{instanceId:input.instanceId,fragmentKey:input.fragmentKey}});}export function castMissionSixVote(client:MissionSixRpcClient,input:{eventSlug:string;deviceKey:string;commandId:string;instanceId:string;vote:'A'|'B'|'C'}):Promise<BunkerCommandReceipt>{if(!['A','B','C'].includes(input.vote))return Promise.reject(new Error('Mission six vote must be A, B or C'));return submitBunkerCommand(client,input.eventSlug,input.deviceKey,input.commandId,{type:'cast_vote',payload:{instanceId:input.instanceId,vote:input.vote}});}export function useMissionSixAbility(client:MissionSixRpcClient,input:{eventSlug:string;deviceKey:string;commandId:string;instanceId:string}):Promise<BunkerCommandReceipt>{return submitBunkerCommand(client,input.eventSlug,input.deviceKey,input.commandId,{type:'use_ability',payload:{instanceId:input.instanceId,problemKey:'protocol'}});}
