import { describe, expect, it, vi } from 'vitest';
import { accelerateTestTimer,fullEventReset,prepareTestGame,resetGameAndRegistrations,seedTestGuests,setTestInventory,setTestWagonState,simulateTestStage } from './testMode.service';

describe('Bunker V2 test mode service',()=>{
 it('seeds only supported rehearsal sizes',async()=>{const rpc=vi.fn().mockResolvedValue({data:{status:'seeded',guestCount:20,wagonCount:3},error:null});await seedTestGuests({rpc},'event',20);expect(rpc).toHaveBeenCalledWith('owner_bunker_v2_seed_test_guests',{p_event_id:'event',p_count:20});await expect(seedTestGuests({rpc},'event',14)).rejects.toThrow(/15/);});
 it('prepares a dedicated test run and never calls production prepare directly',async()=>{const rpc=vi.fn().mockResolvedValue({data:{status:'prepared',gameMode:'test'},error:null});await prepareTestGame({rpc},'event','cmd');expect(rpc).toHaveBeenCalledWith('owner_prepare_bunker_v2_test',{p_event_id:'event',p_command_id:'cmd'});});
 it('exposes explicit test-only helpers',async()=>{const rpc=vi.fn().mockResolvedValue({data:{status:'updated'},error:null});await accelerateTestTimer({rpc},'event',60);await simulateTestStage({rpc},'event');await setTestInventory({rpc},'event',1,'medkit',2);await setTestWagonState({rpc},'event',1,{power:'stable',communication:'working',navigation:'working'});expect(rpc).toHaveBeenCalledTimes(4);});
 it('rejects impossible wagon, inventory and timer values before transport',async()=>{const rpc=vi.fn();await expect(setTestInventory({rpc},'event',6,'medkit',1)).rejects.toThrow(/wagon/i);await expect(setTestInventory({rpc},'event',1,'mystery_box',1)).rejects.toThrow(/inventory/i);await expect(setTestInventory({rpc},'event',1,'water',10)).rejects.toThrow(/quantity/i);await expect(accelerateTestTimer({rpc},'event',601)).rejects.toThrow(/600/);expect(rpc).not.toHaveBeenCalled();});
 it('requires destructive reset phrases before transport',async()=>{const rpc=vi.fn();await expect(resetGameAndRegistrations({rpc},'event','no')).rejects.toThrow(/confirmation/i);await expect(fullEventReset({rpc},'event','no')).rejects.toThrow(/confirmation/i);expect(rpc).not.toHaveBeenCalled();});
});
